#include "glad/gl.h"

GLenum CONST_GL_RENDERER() { return GL_RENDERER; }
GLenum CONST_GL_VERSION() { return GL_VERSION; }
GLenum CONST_GL_VERTEX_SHADER() { return GL_VERTEX_SHADER; }
GLenum CONST_GL_FRAGMENT_SHADER() { return GL_FRAGMENT_SHADER; }
GLenum CONST_GL_ARRAY_BUFFER() { return GL_ARRAY_BUFFER; }
GLenum CONST_GL_STATIC_DRAW() { return GL_STATIC_DRAW; }
GLenum CONST_GL_FLOAT() { return GL_FLOAT; }
GLenum CONST_GL_DEPTH_BUFFER_BIT() { return GL_DEPTH_BUFFER_BIT; }
GLenum CONST_GL_COLOR_BUFFER_BIT() { return GL_COLOR_BUFFER_BIT; }
GLenum CONST_GL_TRIANGLES() { return GL_TRIANGLES; }

GLboolean CONST_GL_TRUE() { return GL_TRUE; }
GLboolean CONST_GL_FALSE() { return GL_FALSE; }