#include "glad/gl.h"

PFNGLACCUMPROC func_glAccum() { return glAccum; }
PFNGLACTIVESHADERPROGRAMPROC func_glActiveShaderProgram() { return glActiveShaderProgram; }
PFNGLACTIVETEXTUREPROC func_glActiveTexture() { return glActiveTexture; }
PFNGLALPHAFUNCPROC func_glAlphaFunc() { return glAlphaFunc; }
PFNGLARETEXTURESRESIDENTPROC func_glAreTexturesResident() { return glAreTexturesResident; }
PFNGLARRAYELEMENTPROC func_glArrayElement() { return glArrayElement; }
PFNGLATTACHSHADERPROC func_glAttachShader() { return glAttachShader; }
PFNGLBEGINPROC func_glBegin() { return glBegin; }
PFNGLBEGINCONDITIONALRENDERPROC func_glBeginConditionalRender() { return glBeginConditionalRender; }
PFNGLBEGINQUERYPROC func_glBeginQuery() { return glBeginQuery; }
PFNGLBEGINQUERYINDEXEDPROC func_glBeginQueryIndexed() { return glBeginQueryIndexed; }
PFNGLBEGINTRANSFORMFEEDBACKPROC func_glBeginTransformFeedback() { return glBeginTransformFeedback; }
PFNGLBINDATTRIBLOCATIONPROC func_glBindAttribLocation() { return glBindAttribLocation; }
PFNGLBINDBUFFERPROC func_glBindBuffer() { return glBindBuffer; }
PFNGLBINDBUFFERBASEPROC func_glBindBufferBase() { return glBindBufferBase; }
PFNGLBINDBUFFERRANGEPROC func_glBindBufferRange() { return glBindBufferRange; }
PFNGLBINDBUFFERSBASEPROC func_glBindBuffersBase() { return glBindBuffersBase; }
PFNGLBINDBUFFERSRANGEPROC func_glBindBuffersRange() { return glBindBuffersRange; }
PFNGLBINDFRAGDATALOCATIONPROC func_glBindFragDataLocation() { return glBindFragDataLocation; }
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC func_glBindFragDataLocationIndexed() { return glBindFragDataLocationIndexed; }
PFNGLBINDFRAMEBUFFERPROC func_glBindFramebuffer() { return glBindFramebuffer; }
PFNGLBINDIMAGETEXTUREPROC func_glBindImageTexture() { return glBindImageTexture; }
PFNGLBINDIMAGETEXTURESPROC func_glBindImageTextures() { return glBindImageTextures; }
PFNGLBINDPROGRAMPIPELINEPROC func_glBindProgramPipeline() { return glBindProgramPipeline; }
PFNGLBINDRENDERBUFFERPROC func_glBindRenderbuffer() { return glBindRenderbuffer; }
PFNGLBINDSAMPLERPROC func_glBindSampler() { return glBindSampler; }
PFNGLBINDSAMPLERSPROC func_glBindSamplers() { return glBindSamplers; }
PFNGLBINDTEXTUREPROC func_glBindTexture() { return glBindTexture; }
PFNGLBINDTEXTUREUNITPROC func_glBindTextureUnit() { return glBindTextureUnit; }
PFNGLBINDTEXTURESPROC func_glBindTextures() { return glBindTextures; }
PFNGLBINDTRANSFORMFEEDBACKPROC func_glBindTransformFeedback() { return glBindTransformFeedback; }
PFNGLBINDVERTEXARRAYPROC func_glBindVertexArray() { return glBindVertexArray; }
PFNGLBINDVERTEXBUFFERPROC func_glBindVertexBuffer() { return glBindVertexBuffer; }
PFNGLBINDVERTEXBUFFERSPROC func_glBindVertexBuffers() { return glBindVertexBuffers; }
PFNGLBITMAPPROC func_glBitmap() { return glBitmap; }
PFNGLBLENDCOLORPROC func_glBlendColor() { return glBlendColor; }
PFNGLBLENDEQUATIONPROC func_glBlendEquation() { return glBlendEquation; }
PFNGLBLENDEQUATIONSEPARATEPROC func_glBlendEquationSeparate() { return glBlendEquationSeparate; }
PFNGLBLENDEQUATIONSEPARATEIPROC func_glBlendEquationSeparatei() { return glBlendEquationSeparatei; }
PFNGLBLENDEQUATIONIPROC func_glBlendEquationi() { return glBlendEquationi; }
PFNGLBLENDFUNCPROC func_glBlendFunc() { return glBlendFunc; }
PFNGLBLENDFUNCSEPARATEPROC func_glBlendFuncSeparate() { return glBlendFuncSeparate; }
PFNGLBLENDFUNCSEPARATEIPROC func_glBlendFuncSeparatei() { return glBlendFuncSeparatei; }
PFNGLBLENDFUNCIPROC func_glBlendFunci() { return glBlendFunci; }
PFNGLBLITFRAMEBUFFERPROC func_glBlitFramebuffer() { return glBlitFramebuffer; }
PFNGLBLITNAMEDFRAMEBUFFERPROC func_glBlitNamedFramebuffer() { return glBlitNamedFramebuffer; }
PFNGLBUFFERDATAPROC func_glBufferData() { return glBufferData; }
PFNGLBUFFERSTORAGEPROC func_glBufferStorage() { return glBufferStorage; }
PFNGLBUFFERSUBDATAPROC func_glBufferSubData() { return glBufferSubData; }
PFNGLCALLLISTPROC func_glCallList() { return glCallList; }
PFNGLCALLLISTSPROC func_glCallLists() { return glCallLists; }
PFNGLCHECKFRAMEBUFFERSTATUSPROC func_glCheckFramebufferStatus() { return glCheckFramebufferStatus; }
PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC func_glCheckNamedFramebufferStatus() { return glCheckNamedFramebufferStatus; }
PFNGLCLAMPCOLORPROC func_glClampColor() { return glClampColor; }
PFNGLCLEARPROC func_glClear() { return glClear; }
PFNGLCLEARACCUMPROC func_glClearAccum() { return glClearAccum; }
PFNGLCLEARBUFFERDATAPROC func_glClearBufferData() { return glClearBufferData; }
PFNGLCLEARBUFFERSUBDATAPROC func_glClearBufferSubData() { return glClearBufferSubData; }
PFNGLCLEARBUFFERFIPROC func_glClearBufferfi() { return glClearBufferfi; }
PFNGLCLEARBUFFERFVPROC func_glClearBufferfv() { return glClearBufferfv; }
PFNGLCLEARBUFFERIVPROC func_glClearBufferiv() { return glClearBufferiv; }
PFNGLCLEARBUFFERUIVPROC func_glClearBufferuiv() { return glClearBufferuiv; }
PFNGLCLEARCOLORPROC func_glClearColor() { return glClearColor; }
PFNGLCLEARDEPTHPROC func_glClearDepth() { return glClearDepth; }
PFNGLCLEARDEPTHFPROC func_glClearDepthf() { return glClearDepthf; }
PFNGLCLEARINDEXPROC func_glClearIndex() { return glClearIndex; }
PFNGLCLEARNAMEDBUFFERDATAPROC func_glClearNamedBufferData() { return glClearNamedBufferData; }
PFNGLCLEARNAMEDBUFFERSUBDATAPROC func_glClearNamedBufferSubData() { return glClearNamedBufferSubData; }
PFNGLCLEARNAMEDFRAMEBUFFERFIPROC func_glClearNamedFramebufferfi() { return glClearNamedFramebufferfi; }
PFNGLCLEARNAMEDFRAMEBUFFERFVPROC func_glClearNamedFramebufferfv() { return glClearNamedFramebufferfv; }
PFNGLCLEARNAMEDFRAMEBUFFERIVPROC func_glClearNamedFramebufferiv() { return glClearNamedFramebufferiv; }
PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC func_glClearNamedFramebufferuiv() { return glClearNamedFramebufferuiv; }
PFNGLCLEARSTENCILPROC func_glClearStencil() { return glClearStencil; }
PFNGLCLEARTEXIMAGEPROC func_glClearTexImage() { return glClearTexImage; }
PFNGLCLEARTEXSUBIMAGEPROC func_glClearTexSubImage() { return glClearTexSubImage; }
PFNGLCLIENTACTIVETEXTUREPROC func_glClientActiveTexture() { return glClientActiveTexture; }
PFNGLCLIENTWAITSYNCPROC func_glClientWaitSync() { return glClientWaitSync; }
PFNGLCLIPCONTROLPROC func_glClipControl() { return glClipControl; }
PFNGLCLIPPLANEPROC func_glClipPlane() { return glClipPlane; }
PFNGLCOLOR3BPROC func_glColor3b() { return glColor3b; }
PFNGLCOLOR3BVPROC func_glColor3bv() { return glColor3bv; }
PFNGLCOLOR3DPROC func_glColor3d() { return glColor3d; }
PFNGLCOLOR3DVPROC func_glColor3dv() { return glColor3dv; }
PFNGLCOLOR3FPROC func_glColor3f() { return glColor3f; }
PFNGLCOLOR3FVPROC func_glColor3fv() { return glColor3fv; }
PFNGLCOLOR3IPROC func_glColor3i() { return glColor3i; }
PFNGLCOLOR3IVPROC func_glColor3iv() { return glColor3iv; }
PFNGLCOLOR3SPROC func_glColor3s() { return glColor3s; }
PFNGLCOLOR3SVPROC func_glColor3sv() { return glColor3sv; }
PFNGLCOLOR3UBPROC func_glColor3ub() { return glColor3ub; }
PFNGLCOLOR3UBVPROC func_glColor3ubv() { return glColor3ubv; }
PFNGLCOLOR3UIPROC func_glColor3ui() { return glColor3ui; }
PFNGLCOLOR3UIVPROC func_glColor3uiv() { return glColor3uiv; }
PFNGLCOLOR3USPROC func_glColor3us() { return glColor3us; }
PFNGLCOLOR3USVPROC func_glColor3usv() { return glColor3usv; }
PFNGLCOLOR4BPROC func_glColor4b() { return glColor4b; }
PFNGLCOLOR4BVPROC func_glColor4bv() { return glColor4bv; }
PFNGLCOLOR4DPROC func_glColor4d() { return glColor4d; }
PFNGLCOLOR4DVPROC func_glColor4dv() { return glColor4dv; }
PFNGLCOLOR4FPROC func_glColor4f() { return glColor4f; }
PFNGLCOLOR4FVPROC func_glColor4fv() { return glColor4fv; }
PFNGLCOLOR4IPROC func_glColor4i() { return glColor4i; }
PFNGLCOLOR4IVPROC func_glColor4iv() { return glColor4iv; }
PFNGLCOLOR4SPROC func_glColor4s() { return glColor4s; }
PFNGLCOLOR4SVPROC func_glColor4sv() { return glColor4sv; }
PFNGLCOLOR4UBPROC func_glColor4ub() { return glColor4ub; }
PFNGLCOLOR4UBVPROC func_glColor4ubv() { return glColor4ubv; }
PFNGLCOLOR4UIPROC func_glColor4ui() { return glColor4ui; }
PFNGLCOLOR4UIVPROC func_glColor4uiv() { return glColor4uiv; }
PFNGLCOLOR4USPROC func_glColor4us() { return glColor4us; }
PFNGLCOLOR4USVPROC func_glColor4usv() { return glColor4usv; }
PFNGLCOLORMASKPROC func_glColorMask() { return glColorMask; }
PFNGLCOLORMASKIPROC func_glColorMaski() { return glColorMaski; }
PFNGLCOLORMATERIALPROC func_glColorMaterial() { return glColorMaterial; }
PFNGLCOLORP3UIPROC func_glColorP3ui() { return glColorP3ui; }
PFNGLCOLORP3UIVPROC func_glColorP3uiv() { return glColorP3uiv; }
PFNGLCOLORP4UIPROC func_glColorP4ui() { return glColorP4ui; }
PFNGLCOLORP4UIVPROC func_glColorP4uiv() { return glColorP4uiv; }
PFNGLCOLORPOINTERPROC func_glColorPointer() { return glColorPointer; }
PFNGLCOMPILESHADERPROC func_glCompileShader() { return glCompileShader; }
PFNGLCOMPRESSEDTEXIMAGE1DPROC func_glCompressedTexImage1D() { return glCompressedTexImage1D; }
PFNGLCOMPRESSEDTEXIMAGE2DPROC func_glCompressedTexImage2D() { return glCompressedTexImage2D; }
PFNGLCOMPRESSEDTEXIMAGE3DPROC func_glCompressedTexImage3D() { return glCompressedTexImage3D; }
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC func_glCompressedTexSubImage1D() { return glCompressedTexSubImage1D; }
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC func_glCompressedTexSubImage2D() { return glCompressedTexSubImage2D; }
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC func_glCompressedTexSubImage3D() { return glCompressedTexSubImage3D; }
PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC func_glCompressedTextureSubImage1D() { return glCompressedTextureSubImage1D; }
PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC func_glCompressedTextureSubImage2D() { return glCompressedTextureSubImage2D; }
PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC func_glCompressedTextureSubImage3D() { return glCompressedTextureSubImage3D; }
PFNGLCOPYBUFFERSUBDATAPROC func_glCopyBufferSubData() { return glCopyBufferSubData; }
PFNGLCOPYIMAGESUBDATAPROC func_glCopyImageSubData() { return glCopyImageSubData; }
PFNGLCOPYNAMEDBUFFERSUBDATAPROC func_glCopyNamedBufferSubData() { return glCopyNamedBufferSubData; }
PFNGLCOPYPIXELSPROC func_glCopyPixels() { return glCopyPixels; }
PFNGLCOPYTEXIMAGE1DPROC func_glCopyTexImage1D() { return glCopyTexImage1D; }
PFNGLCOPYTEXIMAGE2DPROC func_glCopyTexImage2D() { return glCopyTexImage2D; }
PFNGLCOPYTEXSUBIMAGE1DPROC func_glCopyTexSubImage1D() { return glCopyTexSubImage1D; }
PFNGLCOPYTEXSUBIMAGE2DPROC func_glCopyTexSubImage2D() { return glCopyTexSubImage2D; }
PFNGLCOPYTEXSUBIMAGE3DPROC func_glCopyTexSubImage3D() { return glCopyTexSubImage3D; }
PFNGLCOPYTEXTURESUBIMAGE1DPROC func_glCopyTextureSubImage1D() { return glCopyTextureSubImage1D; }
PFNGLCOPYTEXTURESUBIMAGE2DPROC func_glCopyTextureSubImage2D() { return glCopyTextureSubImage2D; }
PFNGLCOPYTEXTURESUBIMAGE3DPROC func_glCopyTextureSubImage3D() { return glCopyTextureSubImage3D; }
PFNGLCREATEBUFFERSPROC func_glCreateBuffers() { return glCreateBuffers; }
PFNGLCREATEFRAMEBUFFERSPROC func_glCreateFramebuffers() { return glCreateFramebuffers; }
PFNGLCREATEPROGRAMPROC func_glCreateProgram() { return glCreateProgram; }
PFNGLCREATEPROGRAMPIPELINESPROC func_glCreateProgramPipelines() { return glCreateProgramPipelines; }
PFNGLCREATEQUERIESPROC func_glCreateQueries() { return glCreateQueries; }
PFNGLCREATERENDERBUFFERSPROC func_glCreateRenderbuffers() { return glCreateRenderbuffers; }
PFNGLCREATESAMPLERSPROC func_glCreateSamplers() { return glCreateSamplers; }
PFNGLCREATESHADERPROC func_glCreateShader() { return glCreateShader; }
PFNGLCREATESHADERPROGRAMVPROC func_glCreateShaderProgramv() { return glCreateShaderProgramv; }
PFNGLCREATETEXTURESPROC func_glCreateTextures() { return glCreateTextures; }
PFNGLCREATETRANSFORMFEEDBACKSPROC func_glCreateTransformFeedbacks() { return glCreateTransformFeedbacks; }
PFNGLCREATEVERTEXARRAYSPROC func_glCreateVertexArrays() { return glCreateVertexArrays; }
PFNGLCULLFACEPROC func_glCullFace() { return glCullFace; }
PFNGLDEBUGMESSAGECALLBACKPROC func_glDebugMessageCallback() { return glDebugMessageCallback; }
PFNGLDEBUGMESSAGECONTROLPROC func_glDebugMessageControl() { return glDebugMessageControl; }
PFNGLDEBUGMESSAGEINSERTPROC func_glDebugMessageInsert() { return glDebugMessageInsert; }
PFNGLDELETEBUFFERSPROC func_glDeleteBuffers() { return glDeleteBuffers; }
PFNGLDELETEFRAMEBUFFERSPROC func_glDeleteFramebuffers() { return glDeleteFramebuffers; }
PFNGLDELETELISTSPROC func_glDeleteLists() { return glDeleteLists; }
PFNGLDELETEPROGRAMPROC func_glDeleteProgram() { return glDeleteProgram; }
PFNGLDELETEPROGRAMPIPELINESPROC func_glDeleteProgramPipelines() { return glDeleteProgramPipelines; }
PFNGLDELETEQUERIESPROC func_glDeleteQueries() { return glDeleteQueries; }
PFNGLDELETERENDERBUFFERSPROC func_glDeleteRenderbuffers() { return glDeleteRenderbuffers; }
PFNGLDELETESAMPLERSPROC func_glDeleteSamplers() { return glDeleteSamplers; }
PFNGLDELETESHADERPROC func_glDeleteShader() { return glDeleteShader; }
PFNGLDELETESYNCPROC func_glDeleteSync() { return glDeleteSync; }
PFNGLDELETETEXTURESPROC func_glDeleteTextures() { return glDeleteTextures; }
PFNGLDELETETRANSFORMFEEDBACKSPROC func_glDeleteTransformFeedbacks() { return glDeleteTransformFeedbacks; }
PFNGLDELETEVERTEXARRAYSPROC func_glDeleteVertexArrays() { return glDeleteVertexArrays; }
PFNGLDEPTHFUNCPROC func_glDepthFunc() { return glDepthFunc; }
PFNGLDEPTHMASKPROC func_glDepthMask() { return glDepthMask; }
PFNGLDEPTHRANGEPROC func_glDepthRange() { return glDepthRange; }
PFNGLDEPTHRANGEARRAYVPROC func_glDepthRangeArrayv() { return glDepthRangeArrayv; }
PFNGLDEPTHRANGEINDEXEDPROC func_glDepthRangeIndexed() { return glDepthRangeIndexed; }
PFNGLDEPTHRANGEFPROC func_glDepthRangef() { return glDepthRangef; }
PFNGLDETACHSHADERPROC func_glDetachShader() { return glDetachShader; }
PFNGLDISABLEPROC func_glDisable() { return glDisable; }
PFNGLDISABLECLIENTSTATEPROC func_glDisableClientState() { return glDisableClientState; }
PFNGLDISABLEVERTEXARRAYATTRIBPROC func_glDisableVertexArrayAttrib() { return glDisableVertexArrayAttrib; }
PFNGLDISABLEVERTEXATTRIBARRAYPROC func_glDisableVertexAttribArray() { return glDisableVertexAttribArray; }
PFNGLDISABLEIPROC func_glDisablei() { return glDisablei; }
PFNGLDISPATCHCOMPUTEPROC func_glDispatchCompute() { return glDispatchCompute; }
PFNGLDISPATCHCOMPUTEINDIRECTPROC func_glDispatchComputeIndirect() { return glDispatchComputeIndirect; }
PFNGLDRAWARRAYSPROC func_glDrawArrays() { return glDrawArrays; }
PFNGLDRAWARRAYSINDIRECTPROC func_glDrawArraysIndirect() { return glDrawArraysIndirect; }
PFNGLDRAWARRAYSINSTANCEDPROC func_glDrawArraysInstanced() { return glDrawArraysInstanced; }
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC func_glDrawArraysInstancedBaseInstance() { return glDrawArraysInstancedBaseInstance; }
PFNGLDRAWBUFFERPROC func_glDrawBuffer() { return glDrawBuffer; }
PFNGLDRAWBUFFERSPROC func_glDrawBuffers() { return glDrawBuffers; }
PFNGLDRAWELEMENTSPROC func_glDrawElements() { return glDrawElements; }
PFNGLDRAWELEMENTSBASEVERTEXPROC func_glDrawElementsBaseVertex() { return glDrawElementsBaseVertex; }
PFNGLDRAWELEMENTSINDIRECTPROC func_glDrawElementsIndirect() { return glDrawElementsIndirect; }
PFNGLDRAWELEMENTSINSTANCEDPROC func_glDrawElementsInstanced() { return glDrawElementsInstanced; }
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC func_glDrawElementsInstancedBaseInstance() { return glDrawElementsInstancedBaseInstance; }
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC func_glDrawElementsInstancedBaseVertex() { return glDrawElementsInstancedBaseVertex; }
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC func_glDrawElementsInstancedBaseVertexBaseInstance() { return glDrawElementsInstancedBaseVertexBaseInstance; }
PFNGLDRAWPIXELSPROC func_glDrawPixels() { return glDrawPixels; }
PFNGLDRAWRANGEELEMENTSPROC func_glDrawRangeElements() { return glDrawRangeElements; }
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC func_glDrawRangeElementsBaseVertex() { return glDrawRangeElementsBaseVertex; }
PFNGLDRAWTRANSFORMFEEDBACKPROC func_glDrawTransformFeedback() { return glDrawTransformFeedback; }
PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC func_glDrawTransformFeedbackInstanced() { return glDrawTransformFeedbackInstanced; }
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC func_glDrawTransformFeedbackStream() { return glDrawTransformFeedbackStream; }
PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC func_glDrawTransformFeedbackStreamInstanced() { return glDrawTransformFeedbackStreamInstanced; }
PFNGLEDGEFLAGPROC func_glEdgeFlag() { return glEdgeFlag; }
PFNGLEDGEFLAGPOINTERPROC func_glEdgeFlagPointer() { return glEdgeFlagPointer; }
PFNGLEDGEFLAGVPROC func_glEdgeFlagv() { return glEdgeFlagv; }
PFNGLENABLEPROC func_glEnable() { return glEnable; }
PFNGLENABLECLIENTSTATEPROC func_glEnableClientState() { return glEnableClientState; }
PFNGLENABLEVERTEXARRAYATTRIBPROC func_glEnableVertexArrayAttrib() { return glEnableVertexArrayAttrib; }
PFNGLENABLEVERTEXATTRIBARRAYPROC func_glEnableVertexAttribArray() { return glEnableVertexAttribArray; }
PFNGLENABLEIPROC func_glEnablei() { return glEnablei; }
PFNGLENDPROC func_glEnd() { return glEnd; }
PFNGLENDCONDITIONALRENDERPROC func_glEndConditionalRender() { return glEndConditionalRender; }
PFNGLENDLISTPROC func_glEndList() { return glEndList; }
PFNGLENDQUERYPROC func_glEndQuery() { return glEndQuery; }
PFNGLENDQUERYINDEXEDPROC func_glEndQueryIndexed() { return glEndQueryIndexed; }
PFNGLENDTRANSFORMFEEDBACKPROC func_glEndTransformFeedback() { return glEndTransformFeedback; }
PFNGLEVALCOORD1DPROC func_glEvalCoord1d() { return glEvalCoord1d; }
PFNGLEVALCOORD1DVPROC func_glEvalCoord1dv() { return glEvalCoord1dv; }
PFNGLEVALCOORD1FPROC func_glEvalCoord1f() { return glEvalCoord1f; }
PFNGLEVALCOORD1FVPROC func_glEvalCoord1fv() { return glEvalCoord1fv; }
PFNGLEVALCOORD2DPROC func_glEvalCoord2d() { return glEvalCoord2d; }
PFNGLEVALCOORD2DVPROC func_glEvalCoord2dv() { return glEvalCoord2dv; }
PFNGLEVALCOORD2FPROC func_glEvalCoord2f() { return glEvalCoord2f; }
PFNGLEVALCOORD2FVPROC func_glEvalCoord2fv() { return glEvalCoord2fv; }
PFNGLEVALMESH1PROC func_glEvalMesh1() { return glEvalMesh1; }
PFNGLEVALMESH2PROC func_glEvalMesh2() { return glEvalMesh2; }
PFNGLEVALPOINT1PROC func_glEvalPoint1() { return glEvalPoint1; }
PFNGLEVALPOINT2PROC func_glEvalPoint2() { return glEvalPoint2; }
PFNGLFEEDBACKBUFFERPROC func_glFeedbackBuffer() { return glFeedbackBuffer; }
PFNGLFENCESYNCPROC func_glFenceSync() { return glFenceSync; }
PFNGLFINISHPROC func_glFinish() { return glFinish; }
PFNGLFLUSHPROC func_glFlush() { return glFlush; }
PFNGLFLUSHMAPPEDBUFFERRANGEPROC func_glFlushMappedBufferRange() { return glFlushMappedBufferRange; }
PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC func_glFlushMappedNamedBufferRange() { return glFlushMappedNamedBufferRange; }
PFNGLFOGCOORDPOINTERPROC func_glFogCoordPointer() { return glFogCoordPointer; }
PFNGLFOGCOORDDPROC func_glFogCoordd() { return glFogCoordd; }
PFNGLFOGCOORDDVPROC func_glFogCoorddv() { return glFogCoorddv; }
PFNGLFOGCOORDFPROC func_glFogCoordf() { return glFogCoordf; }
PFNGLFOGCOORDFVPROC func_glFogCoordfv() { return glFogCoordfv; }
PFNGLFOGFPROC func_glFogf() { return glFogf; }
PFNGLFOGFVPROC func_glFogfv() { return glFogfv; }
PFNGLFOGIPROC func_glFogi() { return glFogi; }
PFNGLFOGIVPROC func_glFogiv() { return glFogiv; }
PFNGLFRAMEBUFFERPARAMETERIPROC func_glFramebufferParameteri() { return glFramebufferParameteri; }
PFNGLFRAMEBUFFERRENDERBUFFERPROC func_glFramebufferRenderbuffer() { return glFramebufferRenderbuffer; }
PFNGLFRAMEBUFFERTEXTUREPROC func_glFramebufferTexture() { return glFramebufferTexture; }
PFNGLFRAMEBUFFERTEXTURE1DPROC func_glFramebufferTexture1D() { return glFramebufferTexture1D; }
PFNGLFRAMEBUFFERTEXTURE2DPROC func_glFramebufferTexture2D() { return glFramebufferTexture2D; }
PFNGLFRAMEBUFFERTEXTURE3DPROC func_glFramebufferTexture3D() { return glFramebufferTexture3D; }
PFNGLFRAMEBUFFERTEXTURELAYERPROC func_glFramebufferTextureLayer() { return glFramebufferTextureLayer; }
PFNGLFRONTFACEPROC func_glFrontFace() { return glFrontFace; }
PFNGLFRUSTUMPROC func_glFrustum() { return glFrustum; }
PFNGLGENBUFFERSPROC func_glGenBuffers() { return glGenBuffers; }
PFNGLGENFRAMEBUFFERSPROC func_glGenFramebuffers() { return glGenFramebuffers; }
PFNGLGENLISTSPROC func_glGenLists() { return glGenLists; }
PFNGLGENPROGRAMPIPELINESPROC func_glGenProgramPipelines() { return glGenProgramPipelines; }
PFNGLGENQUERIESPROC func_glGenQueries() { return glGenQueries; }
PFNGLGENRENDERBUFFERSPROC func_glGenRenderbuffers() { return glGenRenderbuffers; }
PFNGLGENSAMPLERSPROC func_glGenSamplers() { return glGenSamplers; }
PFNGLGENTEXTURESPROC func_glGenTextures() { return glGenTextures; }
PFNGLGENTRANSFORMFEEDBACKSPROC func_glGenTransformFeedbacks() { return glGenTransformFeedbacks; }
PFNGLGENVERTEXARRAYSPROC func_glGenVertexArrays() { return glGenVertexArrays; }
PFNGLGENERATEMIPMAPPROC func_glGenerateMipmap() { return glGenerateMipmap; }
PFNGLGENERATETEXTUREMIPMAPPROC func_glGenerateTextureMipmap() { return glGenerateTextureMipmap; }
PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC func_glGetActiveAtomicCounterBufferiv() { return glGetActiveAtomicCounterBufferiv; }
PFNGLGETACTIVEATTRIBPROC func_glGetActiveAttrib() { return glGetActiveAttrib; }
PFNGLGETACTIVESUBROUTINENAMEPROC func_glGetActiveSubroutineName() { return glGetActiveSubroutineName; }
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC func_glGetActiveSubroutineUniformName() { return glGetActiveSubroutineUniformName; }
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC func_glGetActiveSubroutineUniformiv() { return glGetActiveSubroutineUniformiv; }
PFNGLGETACTIVEUNIFORMPROC func_glGetActiveUniform() { return glGetActiveUniform; }
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC func_glGetActiveUniformBlockName() { return glGetActiveUniformBlockName; }
PFNGLGETACTIVEUNIFORMBLOCKIVPROC func_glGetActiveUniformBlockiv() { return glGetActiveUniformBlockiv; }
PFNGLGETACTIVEUNIFORMNAMEPROC func_glGetActiveUniformName() { return glGetActiveUniformName; }
PFNGLGETACTIVEUNIFORMSIVPROC func_glGetActiveUniformsiv() { return glGetActiveUniformsiv; }
PFNGLGETATTACHEDSHADERSPROC func_glGetAttachedShaders() { return glGetAttachedShaders; }
PFNGLGETATTRIBLOCATIONPROC func_glGetAttribLocation() { return glGetAttribLocation; }
PFNGLGETBOOLEANI_VPROC func_glGetBooleani_v() { return glGetBooleani_v; }
PFNGLGETBOOLEANVPROC func_glGetBooleanv() { return glGetBooleanv; }
PFNGLGETBUFFERPARAMETERI64VPROC func_glGetBufferParameteri64v() { return glGetBufferParameteri64v; }
PFNGLGETBUFFERPARAMETERIVPROC func_glGetBufferParameteriv() { return glGetBufferParameteriv; }
PFNGLGETBUFFERPOINTERVPROC func_glGetBufferPointerv() { return glGetBufferPointerv; }
PFNGLGETBUFFERSUBDATAPROC func_glGetBufferSubData() { return glGetBufferSubData; }
PFNGLGETCLIPPLANEPROC func_glGetClipPlane() { return glGetClipPlane; }
PFNGLGETCOMPRESSEDTEXIMAGEPROC func_glGetCompressedTexImage() { return glGetCompressedTexImage; }
PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC func_glGetCompressedTextureImage() { return glGetCompressedTextureImage; }
PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC func_glGetCompressedTextureSubImage() { return glGetCompressedTextureSubImage; }
PFNGLGETDEBUGMESSAGELOGPROC func_glGetDebugMessageLog() { return glGetDebugMessageLog; }
PFNGLGETDOUBLEI_VPROC func_glGetDoublei_v() { return glGetDoublei_v; }
PFNGLGETDOUBLEVPROC func_glGetDoublev() { return glGetDoublev; }
PFNGLGETERRORPROC func_glGetError() { return glGetError; }
PFNGLGETFLOATI_VPROC func_glGetFloati_v() { return glGetFloati_v; }
PFNGLGETFLOATVPROC func_glGetFloatv() { return glGetFloatv; }
PFNGLGETFRAGDATAINDEXPROC func_glGetFragDataIndex() { return glGetFragDataIndex; }
PFNGLGETFRAGDATALOCATIONPROC func_glGetFragDataLocation() { return glGetFragDataLocation; }
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC func_glGetFramebufferAttachmentParameteriv() { return glGetFramebufferAttachmentParameteriv; }
PFNGLGETFRAMEBUFFERPARAMETERIVPROC func_glGetFramebufferParameteriv() { return glGetFramebufferParameteriv; }
PFNGLGETGRAPHICSRESETSTATUSPROC func_glGetGraphicsResetStatus() { return glGetGraphicsResetStatus; }
PFNGLGETINTEGER64I_VPROC func_glGetInteger64i_v() { return glGetInteger64i_v; }
PFNGLGETINTEGER64VPROC func_glGetInteger64v() { return glGetInteger64v; }
PFNGLGETINTEGERI_VPROC func_glGetIntegeri_v() { return glGetIntegeri_v; }
PFNGLGETINTEGERVPROC func_glGetIntegerv() { return glGetIntegerv; }
PFNGLGETINTERNALFORMATI64VPROC func_glGetInternalformati64v() { return glGetInternalformati64v; }
PFNGLGETINTERNALFORMATIVPROC func_glGetInternalformativ() { return glGetInternalformativ; }
PFNGLGETLIGHTFVPROC func_glGetLightfv() { return glGetLightfv; }
PFNGLGETLIGHTIVPROC func_glGetLightiv() { return glGetLightiv; }
PFNGLGETMAPDVPROC func_glGetMapdv() { return glGetMapdv; }
PFNGLGETMAPFVPROC func_glGetMapfv() { return glGetMapfv; }
PFNGLGETMAPIVPROC func_glGetMapiv() { return glGetMapiv; }
PFNGLGETMATERIALFVPROC func_glGetMaterialfv() { return glGetMaterialfv; }
PFNGLGETMATERIALIVPROC func_glGetMaterialiv() { return glGetMaterialiv; }
PFNGLGETMULTISAMPLEFVPROC func_glGetMultisamplefv() { return glGetMultisamplefv; }
PFNGLGETNAMEDBUFFERPARAMETERI64VPROC func_glGetNamedBufferParameteri64v() { return glGetNamedBufferParameteri64v; }
PFNGLGETNAMEDBUFFERPARAMETERIVPROC func_glGetNamedBufferParameteriv() { return glGetNamedBufferParameteriv; }
PFNGLGETNAMEDBUFFERPOINTERVPROC func_glGetNamedBufferPointerv() { return glGetNamedBufferPointerv; }
PFNGLGETNAMEDBUFFERSUBDATAPROC func_glGetNamedBufferSubData() { return glGetNamedBufferSubData; }
PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC func_glGetNamedFramebufferAttachmentParameteriv() { return glGetNamedFramebufferAttachmentParameteriv; }
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC func_glGetNamedFramebufferParameteriv() { return glGetNamedFramebufferParameteriv; }
PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC func_glGetNamedRenderbufferParameteriv() { return glGetNamedRenderbufferParameteriv; }
PFNGLGETOBJECTLABELPROC func_glGetObjectLabel() { return glGetObjectLabel; }
PFNGLGETOBJECTPTRLABELPROC func_glGetObjectPtrLabel() { return glGetObjectPtrLabel; }
PFNGLGETPIXELMAPFVPROC func_glGetPixelMapfv() { return glGetPixelMapfv; }
PFNGLGETPIXELMAPUIVPROC func_glGetPixelMapuiv() { return glGetPixelMapuiv; }
PFNGLGETPIXELMAPUSVPROC func_glGetPixelMapusv() { return glGetPixelMapusv; }
PFNGLGETPOINTERVPROC func_glGetPointerv() { return glGetPointerv; }
PFNGLGETPOLYGONSTIPPLEPROC func_glGetPolygonStipple() { return glGetPolygonStipple; }
PFNGLGETPROGRAMBINARYPROC func_glGetProgramBinary() { return glGetProgramBinary; }
PFNGLGETPROGRAMINFOLOGPROC func_glGetProgramInfoLog() { return glGetProgramInfoLog; }
PFNGLGETPROGRAMINTERFACEIVPROC func_glGetProgramInterfaceiv() { return glGetProgramInterfaceiv; }
PFNGLGETPROGRAMPIPELINEINFOLOGPROC func_glGetProgramPipelineInfoLog() { return glGetProgramPipelineInfoLog; }
PFNGLGETPROGRAMPIPELINEIVPROC func_glGetProgramPipelineiv() { return glGetProgramPipelineiv; }
PFNGLGETPROGRAMRESOURCEINDEXPROC func_glGetProgramResourceIndex() { return glGetProgramResourceIndex; }
PFNGLGETPROGRAMRESOURCELOCATIONPROC func_glGetProgramResourceLocation() { return glGetProgramResourceLocation; }
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC func_glGetProgramResourceLocationIndex() { return glGetProgramResourceLocationIndex; }
PFNGLGETPROGRAMRESOURCENAMEPROC func_glGetProgramResourceName() { return glGetProgramResourceName; }
PFNGLGETPROGRAMRESOURCEIVPROC func_glGetProgramResourceiv() { return glGetProgramResourceiv; }
PFNGLGETPROGRAMSTAGEIVPROC func_glGetProgramStageiv() { return glGetProgramStageiv; }
PFNGLGETPROGRAMIVPROC func_glGetProgramiv() { return glGetProgramiv; }
PFNGLGETQUERYBUFFEROBJECTI64VPROC func_glGetQueryBufferObjecti64v() { return glGetQueryBufferObjecti64v; }
PFNGLGETQUERYBUFFEROBJECTIVPROC func_glGetQueryBufferObjectiv() { return glGetQueryBufferObjectiv; }
PFNGLGETQUERYBUFFEROBJECTUI64VPROC func_glGetQueryBufferObjectui64v() { return glGetQueryBufferObjectui64v; }
PFNGLGETQUERYBUFFEROBJECTUIVPROC func_glGetQueryBufferObjectuiv() { return glGetQueryBufferObjectuiv; }
PFNGLGETQUERYINDEXEDIVPROC func_glGetQueryIndexediv() { return glGetQueryIndexediv; }
PFNGLGETQUERYOBJECTI64VPROC func_glGetQueryObjecti64v() { return glGetQueryObjecti64v; }
PFNGLGETQUERYOBJECTIVPROC func_glGetQueryObjectiv() { return glGetQueryObjectiv; }
PFNGLGETQUERYOBJECTUI64VPROC func_glGetQueryObjectui64v() { return glGetQueryObjectui64v; }
PFNGLGETQUERYOBJECTUIVPROC func_glGetQueryObjectuiv() { return glGetQueryObjectuiv; }
PFNGLGETQUERYIVPROC func_glGetQueryiv() { return glGetQueryiv; }
PFNGLGETRENDERBUFFERPARAMETERIVPROC func_glGetRenderbufferParameteriv() { return glGetRenderbufferParameteriv; }
PFNGLGETSAMPLERPARAMETERIIVPROC func_glGetSamplerParameterIiv() { return glGetSamplerParameterIiv; }
PFNGLGETSAMPLERPARAMETERIUIVPROC func_glGetSamplerParameterIuiv() { return glGetSamplerParameterIuiv; }
PFNGLGETSAMPLERPARAMETERFVPROC func_glGetSamplerParameterfv() { return glGetSamplerParameterfv; }
PFNGLGETSAMPLERPARAMETERIVPROC func_glGetSamplerParameteriv() { return glGetSamplerParameteriv; }
PFNGLGETSHADERINFOLOGPROC func_glGetShaderInfoLog() { return glGetShaderInfoLog; }
PFNGLGETSHADERPRECISIONFORMATPROC func_glGetShaderPrecisionFormat() { return glGetShaderPrecisionFormat; }
PFNGLGETSHADERSOURCEPROC func_glGetShaderSource() { return glGetShaderSource; }
PFNGLGETSHADERIVPROC func_glGetShaderiv() { return glGetShaderiv; }
PFNGLGETSTRINGPROC func_glGetString() { return glGetString; }
PFNGLGETSTRINGIPROC func_glGetStringi() { return glGetStringi; }
PFNGLGETSUBROUTINEINDEXPROC func_glGetSubroutineIndex() { return glGetSubroutineIndex; }
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC func_glGetSubroutineUniformLocation() { return glGetSubroutineUniformLocation; }
PFNGLGETSYNCIVPROC func_glGetSynciv() { return glGetSynciv; }
PFNGLGETTEXENVFVPROC func_glGetTexEnvfv() { return glGetTexEnvfv; }
PFNGLGETTEXENVIVPROC func_glGetTexEnviv() { return glGetTexEnviv; }
PFNGLGETTEXGENDVPROC func_glGetTexGendv() { return glGetTexGendv; }
PFNGLGETTEXGENFVPROC func_glGetTexGenfv() { return glGetTexGenfv; }
PFNGLGETTEXGENIVPROC func_glGetTexGeniv() { return glGetTexGeniv; }
PFNGLGETTEXIMAGEPROC func_glGetTexImage() { return glGetTexImage; }
PFNGLGETTEXLEVELPARAMETERFVPROC func_glGetTexLevelParameterfv() { return glGetTexLevelParameterfv; }
PFNGLGETTEXLEVELPARAMETERIVPROC func_glGetTexLevelParameteriv() { return glGetTexLevelParameteriv; }
PFNGLGETTEXPARAMETERIIVPROC func_glGetTexParameterIiv() { return glGetTexParameterIiv; }
PFNGLGETTEXPARAMETERIUIVPROC func_glGetTexParameterIuiv() { return glGetTexParameterIuiv; }
PFNGLGETTEXPARAMETERFVPROC func_glGetTexParameterfv() { return glGetTexParameterfv; }
PFNGLGETTEXPARAMETERIVPROC func_glGetTexParameteriv() { return glGetTexParameteriv; }
PFNGLGETTEXTUREIMAGEPROC func_glGetTextureImage() { return glGetTextureImage; }
PFNGLGETTEXTURELEVELPARAMETERFVPROC func_glGetTextureLevelParameterfv() { return glGetTextureLevelParameterfv; }
PFNGLGETTEXTURELEVELPARAMETERIVPROC func_glGetTextureLevelParameteriv() { return glGetTextureLevelParameteriv; }
PFNGLGETTEXTUREPARAMETERIIVPROC func_glGetTextureParameterIiv() { return glGetTextureParameterIiv; }
PFNGLGETTEXTUREPARAMETERIUIVPROC func_glGetTextureParameterIuiv() { return glGetTextureParameterIuiv; }
PFNGLGETTEXTUREPARAMETERFVPROC func_glGetTextureParameterfv() { return glGetTextureParameterfv; }
PFNGLGETTEXTUREPARAMETERIVPROC func_glGetTextureParameteriv() { return glGetTextureParameteriv; }
PFNGLGETTEXTURESUBIMAGEPROC func_glGetTextureSubImage() { return glGetTextureSubImage; }
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC func_glGetTransformFeedbackVarying() { return glGetTransformFeedbackVarying; }
PFNGLGETTRANSFORMFEEDBACKI64_VPROC func_glGetTransformFeedbacki64_v() { return glGetTransformFeedbacki64_v; }
PFNGLGETTRANSFORMFEEDBACKI_VPROC func_glGetTransformFeedbacki_v() { return glGetTransformFeedbacki_v; }
PFNGLGETTRANSFORMFEEDBACKIVPROC func_glGetTransformFeedbackiv() { return glGetTransformFeedbackiv; }
PFNGLGETUNIFORMBLOCKINDEXPROC func_glGetUniformBlockIndex() { return glGetUniformBlockIndex; }
PFNGLGETUNIFORMINDICESPROC func_glGetUniformIndices() { return glGetUniformIndices; }
PFNGLGETUNIFORMLOCATIONPROC func_glGetUniformLocation() { return glGetUniformLocation; }
PFNGLGETUNIFORMSUBROUTINEUIVPROC func_glGetUniformSubroutineuiv() { return glGetUniformSubroutineuiv; }
PFNGLGETUNIFORMDVPROC func_glGetUniformdv() { return glGetUniformdv; }
PFNGLGETUNIFORMFVPROC func_glGetUniformfv() { return glGetUniformfv; }
PFNGLGETUNIFORMIVPROC func_glGetUniformiv() { return glGetUniformiv; }
PFNGLGETUNIFORMUIVPROC func_glGetUniformuiv() { return glGetUniformuiv; }
PFNGLGETVERTEXARRAYINDEXED64IVPROC func_glGetVertexArrayIndexed64iv() { return glGetVertexArrayIndexed64iv; }
PFNGLGETVERTEXARRAYINDEXEDIVPROC func_glGetVertexArrayIndexediv() { return glGetVertexArrayIndexediv; }
PFNGLGETVERTEXARRAYIVPROC func_glGetVertexArrayiv() { return glGetVertexArrayiv; }
PFNGLGETVERTEXATTRIBIIVPROC func_glGetVertexAttribIiv() { return glGetVertexAttribIiv; }
PFNGLGETVERTEXATTRIBIUIVPROC func_glGetVertexAttribIuiv() { return glGetVertexAttribIuiv; }
PFNGLGETVERTEXATTRIBLDVPROC func_glGetVertexAttribLdv() { return glGetVertexAttribLdv; }
PFNGLGETVERTEXATTRIBPOINTERVPROC func_glGetVertexAttribPointerv() { return glGetVertexAttribPointerv; }
PFNGLGETVERTEXATTRIBDVPROC func_glGetVertexAttribdv() { return glGetVertexAttribdv; }
PFNGLGETVERTEXATTRIBFVPROC func_glGetVertexAttribfv() { return glGetVertexAttribfv; }
PFNGLGETVERTEXATTRIBIVPROC func_glGetVertexAttribiv() { return glGetVertexAttribiv; }
PFNGLGETNCOLORTABLEPROC func_glGetnColorTable() { return glGetnColorTable; }
PFNGLGETNCOMPRESSEDTEXIMAGEPROC func_glGetnCompressedTexImage() { return glGetnCompressedTexImage; }
PFNGLGETNCONVOLUTIONFILTERPROC func_glGetnConvolutionFilter() { return glGetnConvolutionFilter; }
PFNGLGETNHISTOGRAMPROC func_glGetnHistogram() { return glGetnHistogram; }
PFNGLGETNMAPDVPROC func_glGetnMapdv() { return glGetnMapdv; }
PFNGLGETNMAPFVPROC func_glGetnMapfv() { return glGetnMapfv; }
PFNGLGETNMAPIVPROC func_glGetnMapiv() { return glGetnMapiv; }
PFNGLGETNMINMAXPROC func_glGetnMinmax() { return glGetnMinmax; }
PFNGLGETNPIXELMAPFVPROC func_glGetnPixelMapfv() { return glGetnPixelMapfv; }
PFNGLGETNPIXELMAPUIVPROC func_glGetnPixelMapuiv() { return glGetnPixelMapuiv; }
PFNGLGETNPIXELMAPUSVPROC func_glGetnPixelMapusv() { return glGetnPixelMapusv; }
PFNGLGETNPOLYGONSTIPPLEPROC func_glGetnPolygonStipple() { return glGetnPolygonStipple; }
PFNGLGETNSEPARABLEFILTERPROC func_glGetnSeparableFilter() { return glGetnSeparableFilter; }
PFNGLGETNTEXIMAGEPROC func_glGetnTexImage() { return glGetnTexImage; }
PFNGLGETNUNIFORMDVPROC func_glGetnUniformdv() { return glGetnUniformdv; }
PFNGLGETNUNIFORMFVPROC func_glGetnUniformfv() { return glGetnUniformfv; }
PFNGLGETNUNIFORMIVPROC func_glGetnUniformiv() { return glGetnUniformiv; }
PFNGLGETNUNIFORMUIVPROC func_glGetnUniformuiv() { return glGetnUniformuiv; }
PFNGLHINTPROC func_glHint() { return glHint; }
PFNGLINDEXMASKPROC func_glIndexMask() { return glIndexMask; }
PFNGLINDEXPOINTERPROC func_glIndexPointer() { return glIndexPointer; }
PFNGLINDEXDPROC func_glIndexd() { return glIndexd; }
PFNGLINDEXDVPROC func_glIndexdv() { return glIndexdv; }
PFNGLINDEXFPROC func_glIndexf() { return glIndexf; }
PFNGLINDEXFVPROC func_glIndexfv() { return glIndexfv; }
PFNGLINDEXIPROC func_glIndexi() { return glIndexi; }
PFNGLINDEXIVPROC func_glIndexiv() { return glIndexiv; }
PFNGLINDEXSPROC func_glIndexs() { return glIndexs; }
PFNGLINDEXSVPROC func_glIndexsv() { return glIndexsv; }
PFNGLINDEXUBPROC func_glIndexub() { return glIndexub; }
PFNGLINDEXUBVPROC func_glIndexubv() { return glIndexubv; }
PFNGLINITNAMESPROC func_glInitNames() { return glInitNames; }
PFNGLINTERLEAVEDARRAYSPROC func_glInterleavedArrays() { return glInterleavedArrays; }
PFNGLINVALIDATEBUFFERDATAPROC func_glInvalidateBufferData() { return glInvalidateBufferData; }
PFNGLINVALIDATEBUFFERSUBDATAPROC func_glInvalidateBufferSubData() { return glInvalidateBufferSubData; }
PFNGLINVALIDATEFRAMEBUFFERPROC func_glInvalidateFramebuffer() { return glInvalidateFramebuffer; }
PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC func_glInvalidateNamedFramebufferData() { return glInvalidateNamedFramebufferData; }
PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC func_glInvalidateNamedFramebufferSubData() { return glInvalidateNamedFramebufferSubData; }
PFNGLINVALIDATESUBFRAMEBUFFERPROC func_glInvalidateSubFramebuffer() { return glInvalidateSubFramebuffer; }
PFNGLINVALIDATETEXIMAGEPROC func_glInvalidateTexImage() { return glInvalidateTexImage; }
PFNGLINVALIDATETEXSUBIMAGEPROC func_glInvalidateTexSubImage() { return glInvalidateTexSubImage; }
PFNGLISBUFFERPROC func_glIsBuffer() { return glIsBuffer; }
PFNGLISENABLEDPROC func_glIsEnabled() { return glIsEnabled; }
PFNGLISENABLEDIPROC func_glIsEnabledi() { return glIsEnabledi; }
PFNGLISFRAMEBUFFERPROC func_glIsFramebuffer() { return glIsFramebuffer; }
PFNGLISLISTPROC func_glIsList() { return glIsList; }
PFNGLISPROGRAMPROC func_glIsProgram() { return glIsProgram; }
PFNGLISPROGRAMPIPELINEPROC func_glIsProgramPipeline() { return glIsProgramPipeline; }
PFNGLISQUERYPROC func_glIsQuery() { return glIsQuery; }
PFNGLISRENDERBUFFERPROC func_glIsRenderbuffer() { return glIsRenderbuffer; }
PFNGLISSAMPLERPROC func_glIsSampler() { return glIsSampler; }
PFNGLISSHADERPROC func_glIsShader() { return glIsShader; }
PFNGLISSYNCPROC func_glIsSync() { return glIsSync; }
PFNGLISTEXTUREPROC func_glIsTexture() { return glIsTexture; }
PFNGLISTRANSFORMFEEDBACKPROC func_glIsTransformFeedback() { return glIsTransformFeedback; }
PFNGLISVERTEXARRAYPROC func_glIsVertexArray() { return glIsVertexArray; }
PFNGLLIGHTMODELFPROC func_glLightModelf() { return glLightModelf; }
PFNGLLIGHTMODELFVPROC func_glLightModelfv() { return glLightModelfv; }
PFNGLLIGHTMODELIPROC func_glLightModeli() { return glLightModeli; }
PFNGLLIGHTMODELIVPROC func_glLightModeliv() { return glLightModeliv; }
PFNGLLIGHTFPROC func_glLightf() { return glLightf; }
PFNGLLIGHTFVPROC func_glLightfv() { return glLightfv; }
PFNGLLIGHTIPROC func_glLighti() { return glLighti; }
PFNGLLIGHTIVPROC func_glLightiv() { return glLightiv; }
PFNGLLINESTIPPLEPROC func_glLineStipple() { return glLineStipple; }
PFNGLLINEWIDTHPROC func_glLineWidth() { return glLineWidth; }
PFNGLLINKPROGRAMPROC func_glLinkProgram() { return glLinkProgram; }
PFNGLLISTBASEPROC func_glListBase() { return glListBase; }
PFNGLLOADIDENTITYPROC func_glLoadIdentity() { return glLoadIdentity; }
PFNGLLOADMATRIXDPROC func_glLoadMatrixd() { return glLoadMatrixd; }
PFNGLLOADMATRIXFPROC func_glLoadMatrixf() { return glLoadMatrixf; }
PFNGLLOADNAMEPROC func_glLoadName() { return glLoadName; }
PFNGLLOADTRANSPOSEMATRIXDPROC func_glLoadTransposeMatrixd() { return glLoadTransposeMatrixd; }
PFNGLLOADTRANSPOSEMATRIXFPROC func_glLoadTransposeMatrixf() { return glLoadTransposeMatrixf; }
PFNGLLOGICOPPROC func_glLogicOp() { return glLogicOp; }
PFNGLMAP1DPROC func_glMap1d() { return glMap1d; }
PFNGLMAP1FPROC func_glMap1f() { return glMap1f; }
PFNGLMAP2DPROC func_glMap2d() { return glMap2d; }
PFNGLMAP2FPROC func_glMap2f() { return glMap2f; }
PFNGLMAPBUFFERPROC func_glMapBuffer() { return glMapBuffer; }
PFNGLMAPBUFFERRANGEPROC func_glMapBufferRange() { return glMapBufferRange; }
PFNGLMAPGRID1DPROC func_glMapGrid1d() { return glMapGrid1d; }
PFNGLMAPGRID1FPROC func_glMapGrid1f() { return glMapGrid1f; }
PFNGLMAPGRID2DPROC func_glMapGrid2d() { return glMapGrid2d; }
PFNGLMAPGRID2FPROC func_glMapGrid2f() { return glMapGrid2f; }
PFNGLMAPNAMEDBUFFERPROC func_glMapNamedBuffer() { return glMapNamedBuffer; }
PFNGLMAPNAMEDBUFFERRANGEPROC func_glMapNamedBufferRange() { return glMapNamedBufferRange; }
PFNGLMATERIALFPROC func_glMaterialf() { return glMaterialf; }
PFNGLMATERIALFVPROC func_glMaterialfv() { return glMaterialfv; }
PFNGLMATERIALIPROC func_glMateriali() { return glMateriali; }
PFNGLMATERIALIVPROC func_glMaterialiv() { return glMaterialiv; }
PFNGLMATRIXMODEPROC func_glMatrixMode() { return glMatrixMode; }
PFNGLMEMORYBARRIERPROC func_glMemoryBarrier() { return glMemoryBarrier; }
PFNGLMEMORYBARRIERBYREGIONPROC func_glMemoryBarrierByRegion() { return glMemoryBarrierByRegion; }
PFNGLMINSAMPLESHADINGPROC func_glMinSampleShading() { return glMinSampleShading; }
PFNGLMULTMATRIXDPROC func_glMultMatrixd() { return glMultMatrixd; }
PFNGLMULTMATRIXFPROC func_glMultMatrixf() { return glMultMatrixf; }
PFNGLMULTTRANSPOSEMATRIXDPROC func_glMultTransposeMatrixd() { return glMultTransposeMatrixd; }
PFNGLMULTTRANSPOSEMATRIXFPROC func_glMultTransposeMatrixf() { return glMultTransposeMatrixf; }
PFNGLMULTIDRAWARRAYSPROC func_glMultiDrawArrays() { return glMultiDrawArrays; }
PFNGLMULTIDRAWARRAYSINDIRECTPROC func_glMultiDrawArraysIndirect() { return glMultiDrawArraysIndirect; }
PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC func_glMultiDrawArraysIndirectCount() { return glMultiDrawArraysIndirectCount; }
PFNGLMULTIDRAWELEMENTSPROC func_glMultiDrawElements() { return glMultiDrawElements; }
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC func_glMultiDrawElementsBaseVertex() { return glMultiDrawElementsBaseVertex; }
PFNGLMULTIDRAWELEMENTSINDIRECTPROC func_glMultiDrawElementsIndirect() { return glMultiDrawElementsIndirect; }
PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC func_glMultiDrawElementsIndirectCount() { return glMultiDrawElementsIndirectCount; }
PFNGLMULTITEXCOORD1DPROC func_glMultiTexCoord1d() { return glMultiTexCoord1d; }
PFNGLMULTITEXCOORD1DVPROC func_glMultiTexCoord1dv() { return glMultiTexCoord1dv; }
PFNGLMULTITEXCOORD1FPROC func_glMultiTexCoord1f() { return glMultiTexCoord1f; }
PFNGLMULTITEXCOORD1FVPROC func_glMultiTexCoord1fv() { return glMultiTexCoord1fv; }
PFNGLMULTITEXCOORD1IPROC func_glMultiTexCoord1i() { return glMultiTexCoord1i; }
PFNGLMULTITEXCOORD1IVPROC func_glMultiTexCoord1iv() { return glMultiTexCoord1iv; }
PFNGLMULTITEXCOORD1SPROC func_glMultiTexCoord1s() { return glMultiTexCoord1s; }
PFNGLMULTITEXCOORD1SVPROC func_glMultiTexCoord1sv() { return glMultiTexCoord1sv; }
PFNGLMULTITEXCOORD2DPROC func_glMultiTexCoord2d() { return glMultiTexCoord2d; }
PFNGLMULTITEXCOORD2DVPROC func_glMultiTexCoord2dv() { return glMultiTexCoord2dv; }
PFNGLMULTITEXCOORD2FPROC func_glMultiTexCoord2f() { return glMultiTexCoord2f; }
PFNGLMULTITEXCOORD2FVPROC func_glMultiTexCoord2fv() { return glMultiTexCoord2fv; }
PFNGLMULTITEXCOORD2IPROC func_glMultiTexCoord2i() { return glMultiTexCoord2i; }
PFNGLMULTITEXCOORD2IVPROC func_glMultiTexCoord2iv() { return glMultiTexCoord2iv; }
PFNGLMULTITEXCOORD2SPROC func_glMultiTexCoord2s() { return glMultiTexCoord2s; }
PFNGLMULTITEXCOORD2SVPROC func_glMultiTexCoord2sv() { return glMultiTexCoord2sv; }
PFNGLMULTITEXCOORD3DPROC func_glMultiTexCoord3d() { return glMultiTexCoord3d; }
PFNGLMULTITEXCOORD3DVPROC func_glMultiTexCoord3dv() { return glMultiTexCoord3dv; }
PFNGLMULTITEXCOORD3FPROC func_glMultiTexCoord3f() { return glMultiTexCoord3f; }
PFNGLMULTITEXCOORD3FVPROC func_glMultiTexCoord3fv() { return glMultiTexCoord3fv; }
PFNGLMULTITEXCOORD3IPROC func_glMultiTexCoord3i() { return glMultiTexCoord3i; }
PFNGLMULTITEXCOORD3IVPROC func_glMultiTexCoord3iv() { return glMultiTexCoord3iv; }
PFNGLMULTITEXCOORD3SPROC func_glMultiTexCoord3s() { return glMultiTexCoord3s; }
PFNGLMULTITEXCOORD3SVPROC func_glMultiTexCoord3sv() { return glMultiTexCoord3sv; }
PFNGLMULTITEXCOORD4DPROC func_glMultiTexCoord4d() { return glMultiTexCoord4d; }
PFNGLMULTITEXCOORD4DVPROC func_glMultiTexCoord4dv() { return glMultiTexCoord4dv; }
PFNGLMULTITEXCOORD4FPROC func_glMultiTexCoord4f() { return glMultiTexCoord4f; }
PFNGLMULTITEXCOORD4FVPROC func_glMultiTexCoord4fv() { return glMultiTexCoord4fv; }
PFNGLMULTITEXCOORD4IPROC func_glMultiTexCoord4i() { return glMultiTexCoord4i; }
PFNGLMULTITEXCOORD4IVPROC func_glMultiTexCoord4iv() { return glMultiTexCoord4iv; }
PFNGLMULTITEXCOORD4SPROC func_glMultiTexCoord4s() { return glMultiTexCoord4s; }
PFNGLMULTITEXCOORD4SVPROC func_glMultiTexCoord4sv() { return glMultiTexCoord4sv; }
PFNGLMULTITEXCOORDP1UIPROC func_glMultiTexCoordP1ui() { return glMultiTexCoordP1ui; }
PFNGLMULTITEXCOORDP1UIVPROC func_glMultiTexCoordP1uiv() { return glMultiTexCoordP1uiv; }
PFNGLMULTITEXCOORDP2UIPROC func_glMultiTexCoordP2ui() { return glMultiTexCoordP2ui; }
PFNGLMULTITEXCOORDP2UIVPROC func_glMultiTexCoordP2uiv() { return glMultiTexCoordP2uiv; }
PFNGLMULTITEXCOORDP3UIPROC func_glMultiTexCoordP3ui() { return glMultiTexCoordP3ui; }
PFNGLMULTITEXCOORDP3UIVPROC func_glMultiTexCoordP3uiv() { return glMultiTexCoordP3uiv; }
PFNGLMULTITEXCOORDP4UIPROC func_glMultiTexCoordP4ui() { return glMultiTexCoordP4ui; }
PFNGLMULTITEXCOORDP4UIVPROC func_glMultiTexCoordP4uiv() { return glMultiTexCoordP4uiv; }
PFNGLNAMEDBUFFERDATAPROC func_glNamedBufferData() { return glNamedBufferData; }
PFNGLNAMEDBUFFERSTORAGEPROC func_glNamedBufferStorage() { return glNamedBufferStorage; }
PFNGLNAMEDBUFFERSUBDATAPROC func_glNamedBufferSubData() { return glNamedBufferSubData; }
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC func_glNamedFramebufferDrawBuffer() { return glNamedFramebufferDrawBuffer; }
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC func_glNamedFramebufferDrawBuffers() { return glNamedFramebufferDrawBuffers; }
PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC func_glNamedFramebufferParameteri() { return glNamedFramebufferParameteri; }
PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC func_glNamedFramebufferReadBuffer() { return glNamedFramebufferReadBuffer; }
PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC func_glNamedFramebufferRenderbuffer() { return glNamedFramebufferRenderbuffer; }
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC func_glNamedFramebufferTexture() { return glNamedFramebufferTexture; }
PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC func_glNamedFramebufferTextureLayer() { return glNamedFramebufferTextureLayer; }
PFNGLNAMEDRENDERBUFFERSTORAGEPROC func_glNamedRenderbufferStorage() { return glNamedRenderbufferStorage; }
PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC func_glNamedRenderbufferStorageMultisample() { return glNamedRenderbufferStorageMultisample; }
PFNGLNEWLISTPROC func_glNewList() { return glNewList; }
PFNGLNORMAL3BPROC func_glNormal3b() { return glNormal3b; }
PFNGLNORMAL3BVPROC func_glNormal3bv() { return glNormal3bv; }
PFNGLNORMAL3DPROC func_glNormal3d() { return glNormal3d; }
PFNGLNORMAL3DVPROC func_glNormal3dv() { return glNormal3dv; }
PFNGLNORMAL3FPROC func_glNormal3f() { return glNormal3f; }
PFNGLNORMAL3FVPROC func_glNormal3fv() { return glNormal3fv; }
PFNGLNORMAL3IPROC func_glNormal3i() { return glNormal3i; }
PFNGLNORMAL3IVPROC func_glNormal3iv() { return glNormal3iv; }
PFNGLNORMAL3SPROC func_glNormal3s() { return glNormal3s; }
PFNGLNORMAL3SVPROC func_glNormal3sv() { return glNormal3sv; }
PFNGLNORMALP3UIPROC func_glNormalP3ui() { return glNormalP3ui; }
PFNGLNORMALP3UIVPROC func_glNormalP3uiv() { return glNormalP3uiv; }
PFNGLNORMALPOINTERPROC func_glNormalPointer() { return glNormalPointer; }
PFNGLOBJECTLABELPROC func_glObjectLabel() { return glObjectLabel; }
PFNGLOBJECTPTRLABELPROC func_glObjectPtrLabel() { return glObjectPtrLabel; }
PFNGLORTHOPROC func_glOrtho() { return glOrtho; }
PFNGLPASSTHROUGHPROC func_glPassThrough() { return glPassThrough; }
PFNGLPATCHPARAMETERFVPROC func_glPatchParameterfv() { return glPatchParameterfv; }
PFNGLPATCHPARAMETERIPROC func_glPatchParameteri() { return glPatchParameteri; }
PFNGLPAUSETRANSFORMFEEDBACKPROC func_glPauseTransformFeedback() { return glPauseTransformFeedback; }
PFNGLPIXELMAPFVPROC func_glPixelMapfv() { return glPixelMapfv; }
PFNGLPIXELMAPUIVPROC func_glPixelMapuiv() { return glPixelMapuiv; }
PFNGLPIXELMAPUSVPROC func_glPixelMapusv() { return glPixelMapusv; }
PFNGLPIXELSTOREFPROC func_glPixelStoref() { return glPixelStoref; }
PFNGLPIXELSTOREIPROC func_glPixelStorei() { return glPixelStorei; }
PFNGLPIXELTRANSFERFPROC func_glPixelTransferf() { return glPixelTransferf; }
PFNGLPIXELTRANSFERIPROC func_glPixelTransferi() { return glPixelTransferi; }
PFNGLPIXELZOOMPROC func_glPixelZoom() { return glPixelZoom; }
PFNGLPOINTPARAMETERFPROC func_glPointParameterf() { return glPointParameterf; }
PFNGLPOINTPARAMETERFVPROC func_glPointParameterfv() { return glPointParameterfv; }
PFNGLPOINTPARAMETERIPROC func_glPointParameteri() { return glPointParameteri; }
PFNGLPOINTPARAMETERIVPROC func_glPointParameteriv() { return glPointParameteriv; }
PFNGLPOINTSIZEPROC func_glPointSize() { return glPointSize; }
PFNGLPOLYGONMODEPROC func_glPolygonMode() { return glPolygonMode; }
PFNGLPOLYGONOFFSETPROC func_glPolygonOffset() { return glPolygonOffset; }
PFNGLPOLYGONOFFSETCLAMPPROC func_glPolygonOffsetClamp() { return glPolygonOffsetClamp; }
PFNGLPOLYGONSTIPPLEPROC func_glPolygonStipple() { return glPolygonStipple; }
PFNGLPOPATTRIBPROC func_glPopAttrib() { return glPopAttrib; }
PFNGLPOPCLIENTATTRIBPROC func_glPopClientAttrib() { return glPopClientAttrib; }
PFNGLPOPDEBUGGROUPPROC func_glPopDebugGroup() { return glPopDebugGroup; }
PFNGLPOPMATRIXPROC func_glPopMatrix() { return glPopMatrix; }
PFNGLPOPNAMEPROC func_glPopName() { return glPopName; }
PFNGLPRIMITIVERESTARTINDEXPROC func_glPrimitiveRestartIndex() { return glPrimitiveRestartIndex; }
PFNGLPRIORITIZETEXTURESPROC func_glPrioritizeTextures() { return glPrioritizeTextures; }
PFNGLPROGRAMBINARYPROC func_glProgramBinary() { return glProgramBinary; }
PFNGLPROGRAMPARAMETERIPROC func_glProgramParameteri() { return glProgramParameteri; }
PFNGLPROGRAMUNIFORM1DPROC func_glProgramUniform1d() { return glProgramUniform1d; }
PFNGLPROGRAMUNIFORM1DVPROC func_glProgramUniform1dv() { return glProgramUniform1dv; }
PFNGLPROGRAMUNIFORM1FPROC func_glProgramUniform1f() { return glProgramUniform1f; }
PFNGLPROGRAMUNIFORM1FVPROC func_glProgramUniform1fv() { return glProgramUniform1fv; }
PFNGLPROGRAMUNIFORM1IPROC func_glProgramUniform1i() { return glProgramUniform1i; }
PFNGLPROGRAMUNIFORM1IVPROC func_glProgramUniform1iv() { return glProgramUniform1iv; }
PFNGLPROGRAMUNIFORM1UIPROC func_glProgramUniform1ui() { return glProgramUniform1ui; }
PFNGLPROGRAMUNIFORM1UIVPROC func_glProgramUniform1uiv() { return glProgramUniform1uiv; }
PFNGLPROGRAMUNIFORM2DPROC func_glProgramUniform2d() { return glProgramUniform2d; }
PFNGLPROGRAMUNIFORM2DVPROC func_glProgramUniform2dv() { return glProgramUniform2dv; }
PFNGLPROGRAMUNIFORM2FPROC func_glProgramUniform2f() { return glProgramUniform2f; }
PFNGLPROGRAMUNIFORM2FVPROC func_glProgramUniform2fv() { return glProgramUniform2fv; }
PFNGLPROGRAMUNIFORM2IPROC func_glProgramUniform2i() { return glProgramUniform2i; }
PFNGLPROGRAMUNIFORM2IVPROC func_glProgramUniform2iv() { return glProgramUniform2iv; }
PFNGLPROGRAMUNIFORM2UIPROC func_glProgramUniform2ui() { return glProgramUniform2ui; }
PFNGLPROGRAMUNIFORM2UIVPROC func_glProgramUniform2uiv() { return glProgramUniform2uiv; }
PFNGLPROGRAMUNIFORM3DPROC func_glProgramUniform3d() { return glProgramUniform3d; }
PFNGLPROGRAMUNIFORM3DVPROC func_glProgramUniform3dv() { return glProgramUniform3dv; }
PFNGLPROGRAMUNIFORM3FPROC func_glProgramUniform3f() { return glProgramUniform3f; }
PFNGLPROGRAMUNIFORM3FVPROC func_glProgramUniform3fv() { return glProgramUniform3fv; }
PFNGLPROGRAMUNIFORM3IPROC func_glProgramUniform3i() { return glProgramUniform3i; }
PFNGLPROGRAMUNIFORM3IVPROC func_glProgramUniform3iv() { return glProgramUniform3iv; }
PFNGLPROGRAMUNIFORM3UIPROC func_glProgramUniform3ui() { return glProgramUniform3ui; }
PFNGLPROGRAMUNIFORM3UIVPROC func_glProgramUniform3uiv() { return glProgramUniform3uiv; }
PFNGLPROGRAMUNIFORM4DPROC func_glProgramUniform4d() { return glProgramUniform4d; }
PFNGLPROGRAMUNIFORM4DVPROC func_glProgramUniform4dv() { return glProgramUniform4dv; }
PFNGLPROGRAMUNIFORM4FPROC func_glProgramUniform4f() { return glProgramUniform4f; }
PFNGLPROGRAMUNIFORM4FVPROC func_glProgramUniform4fv() { return glProgramUniform4fv; }
PFNGLPROGRAMUNIFORM4IPROC func_glProgramUniform4i() { return glProgramUniform4i; }
PFNGLPROGRAMUNIFORM4IVPROC func_glProgramUniform4iv() { return glProgramUniform4iv; }
PFNGLPROGRAMUNIFORM4UIPROC func_glProgramUniform4ui() { return glProgramUniform4ui; }
PFNGLPROGRAMUNIFORM4UIVPROC func_glProgramUniform4uiv() { return glProgramUniform4uiv; }
PFNGLPROGRAMUNIFORMMATRIX2DVPROC func_glProgramUniformMatrix2dv() { return glProgramUniformMatrix2dv; }
PFNGLPROGRAMUNIFORMMATRIX2FVPROC func_glProgramUniformMatrix2fv() { return glProgramUniformMatrix2fv; }
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC func_glProgramUniformMatrix2x3dv() { return glProgramUniformMatrix2x3dv; }
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC func_glProgramUniformMatrix2x3fv() { return glProgramUniformMatrix2x3fv; }
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC func_glProgramUniformMatrix2x4dv() { return glProgramUniformMatrix2x4dv; }
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC func_glProgramUniformMatrix2x4fv() { return glProgramUniformMatrix2x4fv; }
PFNGLPROGRAMUNIFORMMATRIX3DVPROC func_glProgramUniformMatrix3dv() { return glProgramUniformMatrix3dv; }
PFNGLPROGRAMUNIFORMMATRIX3FVPROC func_glProgramUniformMatrix3fv() { return glProgramUniformMatrix3fv; }
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC func_glProgramUniformMatrix3x2dv() { return glProgramUniformMatrix3x2dv; }
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC func_glProgramUniformMatrix3x2fv() { return glProgramUniformMatrix3x2fv; }
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC func_glProgramUniformMatrix3x4dv() { return glProgramUniformMatrix3x4dv; }
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC func_glProgramUniformMatrix3x4fv() { return glProgramUniformMatrix3x4fv; }
PFNGLPROGRAMUNIFORMMATRIX4DVPROC func_glProgramUniformMatrix4dv() { return glProgramUniformMatrix4dv; }
PFNGLPROGRAMUNIFORMMATRIX4FVPROC func_glProgramUniformMatrix4fv() { return glProgramUniformMatrix4fv; }
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC func_glProgramUniformMatrix4x2dv() { return glProgramUniformMatrix4x2dv; }
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC func_glProgramUniformMatrix4x2fv() { return glProgramUniformMatrix4x2fv; }
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC func_glProgramUniformMatrix4x3dv() { return glProgramUniformMatrix4x3dv; }
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC func_glProgramUniformMatrix4x3fv() { return glProgramUniformMatrix4x3fv; }
PFNGLPROVOKINGVERTEXPROC func_glProvokingVertex() { return glProvokingVertex; }
PFNGLPUSHATTRIBPROC func_glPushAttrib() { return glPushAttrib; }
PFNGLPUSHCLIENTATTRIBPROC func_glPushClientAttrib() { return glPushClientAttrib; }
PFNGLPUSHDEBUGGROUPPROC func_glPushDebugGroup() { return glPushDebugGroup; }
PFNGLPUSHMATRIXPROC func_glPushMatrix() { return glPushMatrix; }
PFNGLPUSHNAMEPROC func_glPushName() { return glPushName; }
PFNGLQUERYCOUNTERPROC func_glQueryCounter() { return glQueryCounter; }
PFNGLRASTERPOS2DPROC func_glRasterPos2d() { return glRasterPos2d; }
PFNGLRASTERPOS2DVPROC func_glRasterPos2dv() { return glRasterPos2dv; }
PFNGLRASTERPOS2FPROC func_glRasterPos2f() { return glRasterPos2f; }
PFNGLRASTERPOS2FVPROC func_glRasterPos2fv() { return glRasterPos2fv; }
PFNGLRASTERPOS2IPROC func_glRasterPos2i() { return glRasterPos2i; }
PFNGLRASTERPOS2IVPROC func_glRasterPos2iv() { return glRasterPos2iv; }
PFNGLRASTERPOS2SPROC func_glRasterPos2s() { return glRasterPos2s; }
PFNGLRASTERPOS2SVPROC func_glRasterPos2sv() { return glRasterPos2sv; }
PFNGLRASTERPOS3DPROC func_glRasterPos3d() { return glRasterPos3d; }
PFNGLRASTERPOS3DVPROC func_glRasterPos3dv() { return glRasterPos3dv; }
PFNGLRASTERPOS3FPROC func_glRasterPos3f() { return glRasterPos3f; }
PFNGLRASTERPOS3FVPROC func_glRasterPos3fv() { return glRasterPos3fv; }
PFNGLRASTERPOS3IPROC func_glRasterPos3i() { return glRasterPos3i; }
PFNGLRASTERPOS3IVPROC func_glRasterPos3iv() { return glRasterPos3iv; }
PFNGLRASTERPOS3SPROC func_glRasterPos3s() { return glRasterPos3s; }
PFNGLRASTERPOS3SVPROC func_glRasterPos3sv() { return glRasterPos3sv; }
PFNGLRASTERPOS4DPROC func_glRasterPos4d() { return glRasterPos4d; }
PFNGLRASTERPOS4DVPROC func_glRasterPos4dv() { return glRasterPos4dv; }
PFNGLRASTERPOS4FPROC func_glRasterPos4f() { return glRasterPos4f; }
PFNGLRASTERPOS4FVPROC func_glRasterPos4fv() { return glRasterPos4fv; }
PFNGLRASTERPOS4IPROC func_glRasterPos4i() { return glRasterPos4i; }
PFNGLRASTERPOS4IVPROC func_glRasterPos4iv() { return glRasterPos4iv; }
PFNGLRASTERPOS4SPROC func_glRasterPos4s() { return glRasterPos4s; }
PFNGLRASTERPOS4SVPROC func_glRasterPos4sv() { return glRasterPos4sv; }
PFNGLREADBUFFERPROC func_glReadBuffer() { return glReadBuffer; }
PFNGLREADPIXELSPROC func_glReadPixels() { return glReadPixels; }
PFNGLREADNPIXELSPROC func_glReadnPixels() { return glReadnPixels; }
PFNGLRECTDPROC func_glRectd() { return glRectd; }
PFNGLRECTDVPROC func_glRectdv() { return glRectdv; }
PFNGLRECTFPROC func_glRectf() { return glRectf; }
PFNGLRECTFVPROC func_glRectfv() { return glRectfv; }
PFNGLRECTIPROC func_glRecti() { return glRecti; }
PFNGLRECTIVPROC func_glRectiv() { return glRectiv; }
PFNGLRECTSPROC func_glRects() { return glRects; }
PFNGLRECTSVPROC func_glRectsv() { return glRectsv; }
PFNGLRELEASESHADERCOMPILERPROC func_glReleaseShaderCompiler() { return glReleaseShaderCompiler; }
PFNGLRENDERMODEPROC func_glRenderMode() { return glRenderMode; }
PFNGLRENDERBUFFERSTORAGEPROC func_glRenderbufferStorage() { return glRenderbufferStorage; }
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC func_glRenderbufferStorageMultisample() { return glRenderbufferStorageMultisample; }
PFNGLRESUMETRANSFORMFEEDBACKPROC func_glResumeTransformFeedback() { return glResumeTransformFeedback; }
PFNGLROTATEDPROC func_glRotated() { return glRotated; }
PFNGLROTATEFPROC func_glRotatef() { return glRotatef; }
PFNGLSAMPLECOVERAGEPROC func_glSampleCoverage() { return glSampleCoverage; }
PFNGLSAMPLEMASKIPROC func_glSampleMaski() { return glSampleMaski; }
PFNGLSAMPLERPARAMETERIIVPROC func_glSamplerParameterIiv() { return glSamplerParameterIiv; }
PFNGLSAMPLERPARAMETERIUIVPROC func_glSamplerParameterIuiv() { return glSamplerParameterIuiv; }
PFNGLSAMPLERPARAMETERFPROC func_glSamplerParameterf() { return glSamplerParameterf; }
PFNGLSAMPLERPARAMETERFVPROC func_glSamplerParameterfv() { return glSamplerParameterfv; }
PFNGLSAMPLERPARAMETERIPROC func_glSamplerParameteri() { return glSamplerParameteri; }
PFNGLSAMPLERPARAMETERIVPROC func_glSamplerParameteriv() { return glSamplerParameteriv; }
PFNGLSCALEDPROC func_glScaled() { return glScaled; }
PFNGLSCALEFPROC func_glScalef() { return glScalef; }
PFNGLSCISSORPROC func_glScissor() { return glScissor; }
PFNGLSCISSORARRAYVPROC func_glScissorArrayv() { return glScissorArrayv; }
PFNGLSCISSORINDEXEDPROC func_glScissorIndexed() { return glScissorIndexed; }
PFNGLSCISSORINDEXEDVPROC func_glScissorIndexedv() { return glScissorIndexedv; }
PFNGLSECONDARYCOLOR3BPROC func_glSecondaryColor3b() { return glSecondaryColor3b; }
PFNGLSECONDARYCOLOR3BVPROC func_glSecondaryColor3bv() { return glSecondaryColor3bv; }
PFNGLSECONDARYCOLOR3DPROC func_glSecondaryColor3d() { return glSecondaryColor3d; }
PFNGLSECONDARYCOLOR3DVPROC func_glSecondaryColor3dv() { return glSecondaryColor3dv; }
PFNGLSECONDARYCOLOR3FPROC func_glSecondaryColor3f() { return glSecondaryColor3f; }
PFNGLSECONDARYCOLOR3FVPROC func_glSecondaryColor3fv() { return glSecondaryColor3fv; }
PFNGLSECONDARYCOLOR3IPROC func_glSecondaryColor3i() { return glSecondaryColor3i; }
PFNGLSECONDARYCOLOR3IVPROC func_glSecondaryColor3iv() { return glSecondaryColor3iv; }
PFNGLSECONDARYCOLOR3SPROC func_glSecondaryColor3s() { return glSecondaryColor3s; }
PFNGLSECONDARYCOLOR3SVPROC func_glSecondaryColor3sv() { return glSecondaryColor3sv; }
PFNGLSECONDARYCOLOR3UBPROC func_glSecondaryColor3ub() { return glSecondaryColor3ub; }
PFNGLSECONDARYCOLOR3UBVPROC func_glSecondaryColor3ubv() { return glSecondaryColor3ubv; }
PFNGLSECONDARYCOLOR3UIPROC func_glSecondaryColor3ui() { return glSecondaryColor3ui; }
PFNGLSECONDARYCOLOR3UIVPROC func_glSecondaryColor3uiv() { return glSecondaryColor3uiv; }
PFNGLSECONDARYCOLOR3USPROC func_glSecondaryColor3us() { return glSecondaryColor3us; }
PFNGLSECONDARYCOLOR3USVPROC func_glSecondaryColor3usv() { return glSecondaryColor3usv; }
PFNGLSECONDARYCOLORP3UIPROC func_glSecondaryColorP3ui() { return glSecondaryColorP3ui; }
PFNGLSECONDARYCOLORP3UIVPROC func_glSecondaryColorP3uiv() { return glSecondaryColorP3uiv; }
PFNGLSECONDARYCOLORPOINTERPROC func_glSecondaryColorPointer() { return glSecondaryColorPointer; }
PFNGLSELECTBUFFERPROC func_glSelectBuffer() { return glSelectBuffer; }
PFNGLSHADEMODELPROC func_glShadeModel() { return glShadeModel; }
PFNGLSHADERBINARYPROC func_glShaderBinary() { return glShaderBinary; }
PFNGLSHADERSOURCEPROC func_glShaderSource() { return glShaderSource; }
PFNGLSHADERSTORAGEBLOCKBINDINGPROC func_glShaderStorageBlockBinding() { return glShaderStorageBlockBinding; }
PFNGLSPECIALIZESHADERPROC func_glSpecializeShader() { return glSpecializeShader; }
PFNGLSTENCILFUNCPROC func_glStencilFunc() { return glStencilFunc; }
PFNGLSTENCILFUNCSEPARATEPROC func_glStencilFuncSeparate() { return glStencilFuncSeparate; }
PFNGLSTENCILMASKPROC func_glStencilMask() { return glStencilMask; }
PFNGLSTENCILMASKSEPARATEPROC func_glStencilMaskSeparate() { return glStencilMaskSeparate; }
PFNGLSTENCILOPPROC func_glStencilOp() { return glStencilOp; }
PFNGLSTENCILOPSEPARATEPROC func_glStencilOpSeparate() { return glStencilOpSeparate; }
PFNGLTEXBUFFERPROC func_glTexBuffer() { return glTexBuffer; }
PFNGLTEXBUFFERRANGEPROC func_glTexBufferRange() { return glTexBufferRange; }
PFNGLTEXCOORD1DPROC func_glTexCoord1d() { return glTexCoord1d; }
PFNGLTEXCOORD1DVPROC func_glTexCoord1dv() { return glTexCoord1dv; }
PFNGLTEXCOORD1FPROC func_glTexCoord1f() { return glTexCoord1f; }
PFNGLTEXCOORD1FVPROC func_glTexCoord1fv() { return glTexCoord1fv; }
PFNGLTEXCOORD1IPROC func_glTexCoord1i() { return glTexCoord1i; }
PFNGLTEXCOORD1IVPROC func_glTexCoord1iv() { return glTexCoord1iv; }
PFNGLTEXCOORD1SPROC func_glTexCoord1s() { return glTexCoord1s; }
PFNGLTEXCOORD1SVPROC func_glTexCoord1sv() { return glTexCoord1sv; }
PFNGLTEXCOORD2DPROC func_glTexCoord2d() { return glTexCoord2d; }
PFNGLTEXCOORD2DVPROC func_glTexCoord2dv() { return glTexCoord2dv; }
PFNGLTEXCOORD2FPROC func_glTexCoord2f() { return glTexCoord2f; }
PFNGLTEXCOORD2FVPROC func_glTexCoord2fv() { return glTexCoord2fv; }
PFNGLTEXCOORD2IPROC func_glTexCoord2i() { return glTexCoord2i; }
PFNGLTEXCOORD2IVPROC func_glTexCoord2iv() { return glTexCoord2iv; }
PFNGLTEXCOORD2SPROC func_glTexCoord2s() { return glTexCoord2s; }
PFNGLTEXCOORD2SVPROC func_glTexCoord2sv() { return glTexCoord2sv; }
PFNGLTEXCOORD3DPROC func_glTexCoord3d() { return glTexCoord3d; }
PFNGLTEXCOORD3DVPROC func_glTexCoord3dv() { return glTexCoord3dv; }
PFNGLTEXCOORD3FPROC func_glTexCoord3f() { return glTexCoord3f; }
PFNGLTEXCOORD3FVPROC func_glTexCoord3fv() { return glTexCoord3fv; }
PFNGLTEXCOORD3IPROC func_glTexCoord3i() { return glTexCoord3i; }
PFNGLTEXCOORD3IVPROC func_glTexCoord3iv() { return glTexCoord3iv; }
PFNGLTEXCOORD3SPROC func_glTexCoord3s() { return glTexCoord3s; }
PFNGLTEXCOORD3SVPROC func_glTexCoord3sv() { return glTexCoord3sv; }
PFNGLTEXCOORD4DPROC func_glTexCoord4d() { return glTexCoord4d; }
PFNGLTEXCOORD4DVPROC func_glTexCoord4dv() { return glTexCoord4dv; }
PFNGLTEXCOORD4FPROC func_glTexCoord4f() { return glTexCoord4f; }
PFNGLTEXCOORD4FVPROC func_glTexCoord4fv() { return glTexCoord4fv; }
PFNGLTEXCOORD4IPROC func_glTexCoord4i() { return glTexCoord4i; }
PFNGLTEXCOORD4IVPROC func_glTexCoord4iv() { return glTexCoord4iv; }
PFNGLTEXCOORD4SPROC func_glTexCoord4s() { return glTexCoord4s; }
PFNGLTEXCOORD4SVPROC func_glTexCoord4sv() { return glTexCoord4sv; }
PFNGLTEXCOORDP1UIPROC func_glTexCoordP1ui() { return glTexCoordP1ui; }
PFNGLTEXCOORDP1UIVPROC func_glTexCoordP1uiv() { return glTexCoordP1uiv; }
PFNGLTEXCOORDP2UIPROC func_glTexCoordP2ui() { return glTexCoordP2ui; }
PFNGLTEXCOORDP2UIVPROC func_glTexCoordP2uiv() { return glTexCoordP2uiv; }
PFNGLTEXCOORDP3UIPROC func_glTexCoordP3ui() { return glTexCoordP3ui; }
PFNGLTEXCOORDP3UIVPROC func_glTexCoordP3uiv() { return glTexCoordP3uiv; }
PFNGLTEXCOORDP4UIPROC func_glTexCoordP4ui() { return glTexCoordP4ui; }
PFNGLTEXCOORDP4UIVPROC func_glTexCoordP4uiv() { return glTexCoordP4uiv; }
PFNGLTEXCOORDPOINTERPROC func_glTexCoordPointer() { return glTexCoordPointer; }
PFNGLTEXENVFPROC func_glTexEnvf() { return glTexEnvf; }
PFNGLTEXENVFVPROC func_glTexEnvfv() { return glTexEnvfv; }
PFNGLTEXENVIPROC func_glTexEnvi() { return glTexEnvi; }
PFNGLTEXENVIVPROC func_glTexEnviv() { return glTexEnviv; }
PFNGLTEXGENDPROC func_glTexGend() { return glTexGend; }
PFNGLTEXGENDVPROC func_glTexGendv() { return glTexGendv; }
PFNGLTEXGENFPROC func_glTexGenf() { return glTexGenf; }
PFNGLTEXGENFVPROC func_glTexGenfv() { return glTexGenfv; }
PFNGLTEXGENIPROC func_glTexGeni() { return glTexGeni; }
PFNGLTEXGENIVPROC func_glTexGeniv() { return glTexGeniv; }
PFNGLTEXIMAGE1DPROC func_glTexImage1D() { return glTexImage1D; }
PFNGLTEXIMAGE2DPROC func_glTexImage2D() { return glTexImage2D; }
PFNGLTEXIMAGE2DMULTISAMPLEPROC func_glTexImage2DMultisample() { return glTexImage2DMultisample; }
PFNGLTEXIMAGE3DPROC func_glTexImage3D() { return glTexImage3D; }
PFNGLTEXIMAGE3DMULTISAMPLEPROC func_glTexImage3DMultisample() { return glTexImage3DMultisample; }
PFNGLTEXPARAMETERIIVPROC func_glTexParameterIiv() { return glTexParameterIiv; }
PFNGLTEXPARAMETERIUIVPROC func_glTexParameterIuiv() { return glTexParameterIuiv; }
PFNGLTEXPARAMETERFPROC func_glTexParameterf() { return glTexParameterf; }
PFNGLTEXPARAMETERFVPROC func_glTexParameterfv() { return glTexParameterfv; }
PFNGLTEXPARAMETERIPROC func_glTexParameteri() { return glTexParameteri; }
PFNGLTEXPARAMETERIVPROC func_glTexParameteriv() { return glTexParameteriv; }
PFNGLTEXSTORAGE1DPROC func_glTexStorage1D() { return glTexStorage1D; }
PFNGLTEXSTORAGE2DPROC func_glTexStorage2D() { return glTexStorage2D; }
PFNGLTEXSTORAGE2DMULTISAMPLEPROC func_glTexStorage2DMultisample() { return glTexStorage2DMultisample; }
PFNGLTEXSTORAGE3DPROC func_glTexStorage3D() { return glTexStorage3D; }
PFNGLTEXSTORAGE3DMULTISAMPLEPROC func_glTexStorage3DMultisample() { return glTexStorage3DMultisample; }
PFNGLTEXSUBIMAGE1DPROC func_glTexSubImage1D() { return glTexSubImage1D; }
PFNGLTEXSUBIMAGE2DPROC func_glTexSubImage2D() { return glTexSubImage2D; }
PFNGLTEXSUBIMAGE3DPROC func_glTexSubImage3D() { return glTexSubImage3D; }
PFNGLTEXTUREBARRIERPROC func_glTextureBarrier() { return glTextureBarrier; }
PFNGLTEXTUREBUFFERPROC func_glTextureBuffer() { return glTextureBuffer; }
PFNGLTEXTUREBUFFERRANGEPROC func_glTextureBufferRange() { return glTextureBufferRange; }
PFNGLTEXTUREPARAMETERIIVPROC func_glTextureParameterIiv() { return glTextureParameterIiv; }
PFNGLTEXTUREPARAMETERIUIVPROC func_glTextureParameterIuiv() { return glTextureParameterIuiv; }
PFNGLTEXTUREPARAMETERFPROC func_glTextureParameterf() { return glTextureParameterf; }
PFNGLTEXTUREPARAMETERFVPROC func_glTextureParameterfv() { return glTextureParameterfv; }
PFNGLTEXTUREPARAMETERIPROC func_glTextureParameteri() { return glTextureParameteri; }
PFNGLTEXTUREPARAMETERIVPROC func_glTextureParameteriv() { return glTextureParameteriv; }
PFNGLTEXTURESTORAGE1DPROC func_glTextureStorage1D() { return glTextureStorage1D; }
PFNGLTEXTURESTORAGE2DPROC func_glTextureStorage2D() { return glTextureStorage2D; }
PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC func_glTextureStorage2DMultisample() { return glTextureStorage2DMultisample; }
PFNGLTEXTURESTORAGE3DPROC func_glTextureStorage3D() { return glTextureStorage3D; }
PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC func_glTextureStorage3DMultisample() { return glTextureStorage3DMultisample; }
PFNGLTEXTURESUBIMAGE1DPROC func_glTextureSubImage1D() { return glTextureSubImage1D; }
PFNGLTEXTURESUBIMAGE2DPROC func_glTextureSubImage2D() { return glTextureSubImage2D; }
PFNGLTEXTURESUBIMAGE3DPROC func_glTextureSubImage3D() { return glTextureSubImage3D; }
PFNGLTEXTUREVIEWPROC func_glTextureView() { return glTextureView; }
PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC func_glTransformFeedbackBufferBase() { return glTransformFeedbackBufferBase; }
PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC func_glTransformFeedbackBufferRange() { return glTransformFeedbackBufferRange; }
PFNGLTRANSFORMFEEDBACKVARYINGSPROC func_glTransformFeedbackVaryings() { return glTransformFeedbackVaryings; }
PFNGLTRANSLATEDPROC func_glTranslated() { return glTranslated; }
PFNGLTRANSLATEFPROC func_glTranslatef() { return glTranslatef; }
PFNGLUNIFORM1DPROC func_glUniform1d() { return glUniform1d; }
PFNGLUNIFORM1DVPROC func_glUniform1dv() { return glUniform1dv; }
PFNGLUNIFORM1FPROC func_glUniform1f() { return glUniform1f; }
PFNGLUNIFORM1FVPROC func_glUniform1fv() { return glUniform1fv; }
PFNGLUNIFORM1IPROC func_glUniform1i() { return glUniform1i; }
PFNGLUNIFORM1IVPROC func_glUniform1iv() { return glUniform1iv; }
PFNGLUNIFORM1UIPROC func_glUniform1ui() { return glUniform1ui; }
PFNGLUNIFORM1UIVPROC func_glUniform1uiv() { return glUniform1uiv; }
PFNGLUNIFORM2DPROC func_glUniform2d() { return glUniform2d; }
PFNGLUNIFORM2DVPROC func_glUniform2dv() { return glUniform2dv; }
PFNGLUNIFORM2FPROC func_glUniform2f() { return glUniform2f; }
PFNGLUNIFORM2FVPROC func_glUniform2fv() { return glUniform2fv; }
PFNGLUNIFORM2IPROC func_glUniform2i() { return glUniform2i; }
PFNGLUNIFORM2IVPROC func_glUniform2iv() { return glUniform2iv; }
PFNGLUNIFORM2UIPROC func_glUniform2ui() { return glUniform2ui; }
PFNGLUNIFORM2UIVPROC func_glUniform2uiv() { return glUniform2uiv; }
PFNGLUNIFORM3DPROC func_glUniform3d() { return glUniform3d; }
PFNGLUNIFORM3DVPROC func_glUniform3dv() { return glUniform3dv; }
PFNGLUNIFORM3FPROC func_glUniform3f() { return glUniform3f; }
PFNGLUNIFORM3FVPROC func_glUniform3fv() { return glUniform3fv; }
PFNGLUNIFORM3IPROC func_glUniform3i() { return glUniform3i; }
PFNGLUNIFORM3IVPROC func_glUniform3iv() { return glUniform3iv; }
PFNGLUNIFORM3UIPROC func_glUniform3ui() { return glUniform3ui; }
PFNGLUNIFORM3UIVPROC func_glUniform3uiv() { return glUniform3uiv; }
PFNGLUNIFORM4DPROC func_glUniform4d() { return glUniform4d; }
PFNGLUNIFORM4DVPROC func_glUniform4dv() { return glUniform4dv; }
PFNGLUNIFORM4FPROC func_glUniform4f() { return glUniform4f; }
PFNGLUNIFORM4FVPROC func_glUniform4fv() { return glUniform4fv; }
PFNGLUNIFORM4IPROC func_glUniform4i() { return glUniform4i; }
PFNGLUNIFORM4IVPROC func_glUniform4iv() { return glUniform4iv; }
PFNGLUNIFORM4UIPROC func_glUniform4ui() { return glUniform4ui; }
PFNGLUNIFORM4UIVPROC func_glUniform4uiv() { return glUniform4uiv; }
PFNGLUNIFORMBLOCKBINDINGPROC func_glUniformBlockBinding() { return glUniformBlockBinding; }
PFNGLUNIFORMMATRIX2DVPROC func_glUniformMatrix2dv() { return glUniformMatrix2dv; }
PFNGLUNIFORMMATRIX2FVPROC func_glUniformMatrix2fv() { return glUniformMatrix2fv; }
PFNGLUNIFORMMATRIX2X3DVPROC func_glUniformMatrix2x3dv() { return glUniformMatrix2x3dv; }
PFNGLUNIFORMMATRIX2X3FVPROC func_glUniformMatrix2x3fv() { return glUniformMatrix2x3fv; }
PFNGLUNIFORMMATRIX2X4DVPROC func_glUniformMatrix2x4dv() { return glUniformMatrix2x4dv; }
PFNGLUNIFORMMATRIX2X4FVPROC func_glUniformMatrix2x4fv() { return glUniformMatrix2x4fv; }
PFNGLUNIFORMMATRIX3DVPROC func_glUniformMatrix3dv() { return glUniformMatrix3dv; }
PFNGLUNIFORMMATRIX3FVPROC func_glUniformMatrix3fv() { return glUniformMatrix3fv; }
PFNGLUNIFORMMATRIX3X2DVPROC func_glUniformMatrix3x2dv() { return glUniformMatrix3x2dv; }
PFNGLUNIFORMMATRIX3X2FVPROC func_glUniformMatrix3x2fv() { return glUniformMatrix3x2fv; }
PFNGLUNIFORMMATRIX3X4DVPROC func_glUniformMatrix3x4dv() { return glUniformMatrix3x4dv; }
PFNGLUNIFORMMATRIX3X4FVPROC func_glUniformMatrix3x4fv() { return glUniformMatrix3x4fv; }
PFNGLUNIFORMMATRIX4DVPROC func_glUniformMatrix4dv() { return glUniformMatrix4dv; }
PFNGLUNIFORMMATRIX4FVPROC func_glUniformMatrix4fv() { return glUniformMatrix4fv; }
PFNGLUNIFORMMATRIX4X2DVPROC func_glUniformMatrix4x2dv() { return glUniformMatrix4x2dv; }
PFNGLUNIFORMMATRIX4X2FVPROC func_glUniformMatrix4x2fv() { return glUniformMatrix4x2fv; }
PFNGLUNIFORMMATRIX4X3DVPROC func_glUniformMatrix4x3dv() { return glUniformMatrix4x3dv; }
PFNGLUNIFORMMATRIX4X3FVPROC func_glUniformMatrix4x3fv() { return glUniformMatrix4x3fv; }
PFNGLUNIFORMSUBROUTINESUIVPROC func_glUniformSubroutinesuiv() { return glUniformSubroutinesuiv; }
PFNGLUNMAPBUFFERPROC func_glUnmapBuffer() { return glUnmapBuffer; }
PFNGLUNMAPNAMEDBUFFERPROC func_glUnmapNamedBuffer() { return glUnmapNamedBuffer; }
PFNGLUSEPROGRAMPROC func_glUseProgram() { return glUseProgram; }
PFNGLUSEPROGRAMSTAGESPROC func_glUseProgramStages() { return glUseProgramStages; }
PFNGLVALIDATEPROGRAMPROC func_glValidateProgram() { return glValidateProgram; }
PFNGLVALIDATEPROGRAMPIPELINEPROC func_glValidateProgramPipeline() { return glValidateProgramPipeline; }
PFNGLVERTEX2DPROC func_glVertex2d() { return glVertex2d; }
PFNGLVERTEX2DVPROC func_glVertex2dv() { return glVertex2dv; }
PFNGLVERTEX2FPROC func_glVertex2f() { return glVertex2f; }
PFNGLVERTEX2FVPROC func_glVertex2fv() { return glVertex2fv; }
PFNGLVERTEX2IPROC func_glVertex2i() { return glVertex2i; }
PFNGLVERTEX2IVPROC func_glVertex2iv() { return glVertex2iv; }
PFNGLVERTEX2SPROC func_glVertex2s() { return glVertex2s; }
PFNGLVERTEX2SVPROC func_glVertex2sv() { return glVertex2sv; }
PFNGLVERTEX3DPROC func_glVertex3d() { return glVertex3d; }
PFNGLVERTEX3DVPROC func_glVertex3dv() { return glVertex3dv; }
PFNGLVERTEX3FPROC func_glVertex3f() { return glVertex3f; }
PFNGLVERTEX3FVPROC func_glVertex3fv() { return glVertex3fv; }
PFNGLVERTEX3IPROC func_glVertex3i() { return glVertex3i; }
PFNGLVERTEX3IVPROC func_glVertex3iv() { return glVertex3iv; }
PFNGLVERTEX3SPROC func_glVertex3s() { return glVertex3s; }
PFNGLVERTEX3SVPROC func_glVertex3sv() { return glVertex3sv; }
PFNGLVERTEX4DPROC func_glVertex4d() { return glVertex4d; }
PFNGLVERTEX4DVPROC func_glVertex4dv() { return glVertex4dv; }
PFNGLVERTEX4FPROC func_glVertex4f() { return glVertex4f; }
PFNGLVERTEX4FVPROC func_glVertex4fv() { return glVertex4fv; }
PFNGLVERTEX4IPROC func_glVertex4i() { return glVertex4i; }
PFNGLVERTEX4IVPROC func_glVertex4iv() { return glVertex4iv; }
PFNGLVERTEX4SPROC func_glVertex4s() { return glVertex4s; }
PFNGLVERTEX4SVPROC func_glVertex4sv() { return glVertex4sv; }
PFNGLVERTEXARRAYATTRIBBINDINGPROC func_glVertexArrayAttribBinding() { return glVertexArrayAttribBinding; }
PFNGLVERTEXARRAYATTRIBFORMATPROC func_glVertexArrayAttribFormat() { return glVertexArrayAttribFormat; }
PFNGLVERTEXARRAYATTRIBIFORMATPROC func_glVertexArrayAttribIFormat() { return glVertexArrayAttribIFormat; }
PFNGLVERTEXARRAYATTRIBLFORMATPROC func_glVertexArrayAttribLFormat() { return glVertexArrayAttribLFormat; }
PFNGLVERTEXARRAYBINDINGDIVISORPROC func_glVertexArrayBindingDivisor() { return glVertexArrayBindingDivisor; }
PFNGLVERTEXARRAYELEMENTBUFFERPROC func_glVertexArrayElementBuffer() { return glVertexArrayElementBuffer; }
PFNGLVERTEXARRAYVERTEXBUFFERPROC func_glVertexArrayVertexBuffer() { return glVertexArrayVertexBuffer; }
PFNGLVERTEXARRAYVERTEXBUFFERSPROC func_glVertexArrayVertexBuffers() { return glVertexArrayVertexBuffers; }
PFNGLVERTEXATTRIB1DPROC func_glVertexAttrib1d() { return glVertexAttrib1d; }
PFNGLVERTEXATTRIB1DVPROC func_glVertexAttrib1dv() { return glVertexAttrib1dv; }
PFNGLVERTEXATTRIB1FPROC func_glVertexAttrib1f() { return glVertexAttrib1f; }
PFNGLVERTEXATTRIB1FVPROC func_glVertexAttrib1fv() { return glVertexAttrib1fv; }
PFNGLVERTEXATTRIB1SPROC func_glVertexAttrib1s() { return glVertexAttrib1s; }
PFNGLVERTEXATTRIB1SVPROC func_glVertexAttrib1sv() { return glVertexAttrib1sv; }
PFNGLVERTEXATTRIB2DPROC func_glVertexAttrib2d() { return glVertexAttrib2d; }
PFNGLVERTEXATTRIB2DVPROC func_glVertexAttrib2dv() { return glVertexAttrib2dv; }
PFNGLVERTEXATTRIB2FPROC func_glVertexAttrib2f() { return glVertexAttrib2f; }
PFNGLVERTEXATTRIB2FVPROC func_glVertexAttrib2fv() { return glVertexAttrib2fv; }
PFNGLVERTEXATTRIB2SPROC func_glVertexAttrib2s() { return glVertexAttrib2s; }
PFNGLVERTEXATTRIB2SVPROC func_glVertexAttrib2sv() { return glVertexAttrib2sv; }
PFNGLVERTEXATTRIB3DPROC func_glVertexAttrib3d() { return glVertexAttrib3d; }
PFNGLVERTEXATTRIB3DVPROC func_glVertexAttrib3dv() { return glVertexAttrib3dv; }
PFNGLVERTEXATTRIB3FPROC func_glVertexAttrib3f() { return glVertexAttrib3f; }
PFNGLVERTEXATTRIB3FVPROC func_glVertexAttrib3fv() { return glVertexAttrib3fv; }
PFNGLVERTEXATTRIB3SPROC func_glVertexAttrib3s() { return glVertexAttrib3s; }
PFNGLVERTEXATTRIB3SVPROC func_glVertexAttrib3sv() { return glVertexAttrib3sv; }
PFNGLVERTEXATTRIB4NBVPROC func_glVertexAttrib4Nbv() { return glVertexAttrib4Nbv; }
PFNGLVERTEXATTRIB4NIVPROC func_glVertexAttrib4Niv() { return glVertexAttrib4Niv; }
PFNGLVERTEXATTRIB4NSVPROC func_glVertexAttrib4Nsv() { return glVertexAttrib4Nsv; }
PFNGLVERTEXATTRIB4NUBPROC func_glVertexAttrib4Nub() { return glVertexAttrib4Nub; }
PFNGLVERTEXATTRIB4NUBVPROC func_glVertexAttrib4Nubv() { return glVertexAttrib4Nubv; }
PFNGLVERTEXATTRIB4NUIVPROC func_glVertexAttrib4Nuiv() { return glVertexAttrib4Nuiv; }
PFNGLVERTEXATTRIB4NUSVPROC func_glVertexAttrib4Nusv() { return glVertexAttrib4Nusv; }
PFNGLVERTEXATTRIB4BVPROC func_glVertexAttrib4bv() { return glVertexAttrib4bv; }
PFNGLVERTEXATTRIB4DPROC func_glVertexAttrib4d() { return glVertexAttrib4d; }
PFNGLVERTEXATTRIB4DVPROC func_glVertexAttrib4dv() { return glVertexAttrib4dv; }
PFNGLVERTEXATTRIB4FPROC func_glVertexAttrib4f() { return glVertexAttrib4f; }
PFNGLVERTEXATTRIB4FVPROC func_glVertexAttrib4fv() { return glVertexAttrib4fv; }
PFNGLVERTEXATTRIB4IVPROC func_glVertexAttrib4iv() { return glVertexAttrib4iv; }
PFNGLVERTEXATTRIB4SPROC func_glVertexAttrib4s() { return glVertexAttrib4s; }
PFNGLVERTEXATTRIB4SVPROC func_glVertexAttrib4sv() { return glVertexAttrib4sv; }
PFNGLVERTEXATTRIB4UBVPROC func_glVertexAttrib4ubv() { return glVertexAttrib4ubv; }
PFNGLVERTEXATTRIB4UIVPROC func_glVertexAttrib4uiv() { return glVertexAttrib4uiv; }
PFNGLVERTEXATTRIB4USVPROC func_glVertexAttrib4usv() { return glVertexAttrib4usv; }
PFNGLVERTEXATTRIBBINDINGPROC func_glVertexAttribBinding() { return glVertexAttribBinding; }
PFNGLVERTEXATTRIBDIVISORPROC func_glVertexAttribDivisor() { return glVertexAttribDivisor; }
PFNGLVERTEXATTRIBFORMATPROC func_glVertexAttribFormat() { return glVertexAttribFormat; }
PFNGLVERTEXATTRIBI1IPROC func_glVertexAttribI1i() { return glVertexAttribI1i; }
PFNGLVERTEXATTRIBI1IVPROC func_glVertexAttribI1iv() { return glVertexAttribI1iv; }
PFNGLVERTEXATTRIBI1UIPROC func_glVertexAttribI1ui() { return glVertexAttribI1ui; }
PFNGLVERTEXATTRIBI1UIVPROC func_glVertexAttribI1uiv() { return glVertexAttribI1uiv; }
PFNGLVERTEXATTRIBI2IPROC func_glVertexAttribI2i() { return glVertexAttribI2i; }
PFNGLVERTEXATTRIBI2IVPROC func_glVertexAttribI2iv() { return glVertexAttribI2iv; }
PFNGLVERTEXATTRIBI2UIPROC func_glVertexAttribI2ui() { return glVertexAttribI2ui; }
PFNGLVERTEXATTRIBI2UIVPROC func_glVertexAttribI2uiv() { return glVertexAttribI2uiv; }
PFNGLVERTEXATTRIBI3IPROC func_glVertexAttribI3i() { return glVertexAttribI3i; }
PFNGLVERTEXATTRIBI3IVPROC func_glVertexAttribI3iv() { return glVertexAttribI3iv; }
PFNGLVERTEXATTRIBI3UIPROC func_glVertexAttribI3ui() { return glVertexAttribI3ui; }
PFNGLVERTEXATTRIBI3UIVPROC func_glVertexAttribI3uiv() { return glVertexAttribI3uiv; }
PFNGLVERTEXATTRIBI4BVPROC func_glVertexAttribI4bv() { return glVertexAttribI4bv; }
PFNGLVERTEXATTRIBI4IPROC func_glVertexAttribI4i() { return glVertexAttribI4i; }
PFNGLVERTEXATTRIBI4IVPROC func_glVertexAttribI4iv() { return glVertexAttribI4iv; }
PFNGLVERTEXATTRIBI4SVPROC func_glVertexAttribI4sv() { return glVertexAttribI4sv; }
PFNGLVERTEXATTRIBI4UBVPROC func_glVertexAttribI4ubv() { return glVertexAttribI4ubv; }
PFNGLVERTEXATTRIBI4UIPROC func_glVertexAttribI4ui() { return glVertexAttribI4ui; }
PFNGLVERTEXATTRIBI4UIVPROC func_glVertexAttribI4uiv() { return glVertexAttribI4uiv; }
PFNGLVERTEXATTRIBI4USVPROC func_glVertexAttribI4usv() { return glVertexAttribI4usv; }
PFNGLVERTEXATTRIBIFORMATPROC func_glVertexAttribIFormat() { return glVertexAttribIFormat; }
PFNGLVERTEXATTRIBIPOINTERPROC func_glVertexAttribIPointer() { return glVertexAttribIPointer; }
PFNGLVERTEXATTRIBL1DPROC func_glVertexAttribL1d() { return glVertexAttribL1d; }
PFNGLVERTEXATTRIBL1DVPROC func_glVertexAttribL1dv() { return glVertexAttribL1dv; }
PFNGLVERTEXATTRIBL2DPROC func_glVertexAttribL2d() { return glVertexAttribL2d; }
PFNGLVERTEXATTRIBL2DVPROC func_glVertexAttribL2dv() { return glVertexAttribL2dv; }
PFNGLVERTEXATTRIBL3DPROC func_glVertexAttribL3d() { return glVertexAttribL3d; }
PFNGLVERTEXATTRIBL3DVPROC func_glVertexAttribL3dv() { return glVertexAttribL3dv; }
PFNGLVERTEXATTRIBL4DPROC func_glVertexAttribL4d() { return glVertexAttribL4d; }
PFNGLVERTEXATTRIBL4DVPROC func_glVertexAttribL4dv() { return glVertexAttribL4dv; }
PFNGLVERTEXATTRIBLFORMATPROC func_glVertexAttribLFormat() { return glVertexAttribLFormat; }
PFNGLVERTEXATTRIBLPOINTERPROC func_glVertexAttribLPointer() { return glVertexAttribLPointer; }
PFNGLVERTEXATTRIBP1UIPROC func_glVertexAttribP1ui() { return glVertexAttribP1ui; }
PFNGLVERTEXATTRIBP1UIVPROC func_glVertexAttribP1uiv() { return glVertexAttribP1uiv; }
PFNGLVERTEXATTRIBP2UIPROC func_glVertexAttribP2ui() { return glVertexAttribP2ui; }
PFNGLVERTEXATTRIBP2UIVPROC func_glVertexAttribP2uiv() { return glVertexAttribP2uiv; }
PFNGLVERTEXATTRIBP3UIPROC func_glVertexAttribP3ui() { return glVertexAttribP3ui; }
PFNGLVERTEXATTRIBP3UIVPROC func_glVertexAttribP3uiv() { return glVertexAttribP3uiv; }
PFNGLVERTEXATTRIBP4UIPROC func_glVertexAttribP4ui() { return glVertexAttribP4ui; }
PFNGLVERTEXATTRIBP4UIVPROC func_glVertexAttribP4uiv() { return glVertexAttribP4uiv; }
PFNGLVERTEXATTRIBPOINTERPROC func_glVertexAttribPointer() { return glVertexAttribPointer; }
PFNGLVERTEXBINDINGDIVISORPROC func_glVertexBindingDivisor() { return glVertexBindingDivisor; }
PFNGLVERTEXP2UIPROC func_glVertexP2ui() { return glVertexP2ui; }
PFNGLVERTEXP2UIVPROC func_glVertexP2uiv() { return glVertexP2uiv; }
PFNGLVERTEXP3UIPROC func_glVertexP3ui() { return glVertexP3ui; }
PFNGLVERTEXP3UIVPROC func_glVertexP3uiv() { return glVertexP3uiv; }
PFNGLVERTEXP4UIPROC func_glVertexP4ui() { return glVertexP4ui; }
PFNGLVERTEXP4UIVPROC func_glVertexP4uiv() { return glVertexP4uiv; }
PFNGLVERTEXPOINTERPROC func_glVertexPointer() { return glVertexPointer; }
PFNGLVIEWPORTPROC func_glViewport() { return glViewport; }
PFNGLVIEWPORTARRAYVPROC func_glViewportArrayv() { return glViewportArrayv; }
PFNGLVIEWPORTINDEXEDFPROC func_glViewportIndexedf() { return glViewportIndexedf; }
PFNGLVIEWPORTINDEXEDFVPROC func_glViewportIndexedfv() { return glViewportIndexedfv; }
PFNGLWAITSYNCPROC func_glWaitSync() { return glWaitSync; }
PFNGLWINDOWPOS2DPROC func_glWindowPos2d() { return glWindowPos2d; }
PFNGLWINDOWPOS2DVPROC func_glWindowPos2dv() { return glWindowPos2dv; }
PFNGLWINDOWPOS2FPROC func_glWindowPos2f() { return glWindowPos2f; }
PFNGLWINDOWPOS2FVPROC func_glWindowPos2fv() { return glWindowPos2fv; }
PFNGLWINDOWPOS2IPROC func_glWindowPos2i() { return glWindowPos2i; }
PFNGLWINDOWPOS2IVPROC func_glWindowPos2iv() { return glWindowPos2iv; }
PFNGLWINDOWPOS2SPROC func_glWindowPos2s() { return glWindowPos2s; }
PFNGLWINDOWPOS2SVPROC func_glWindowPos2sv() { return glWindowPos2sv; }
PFNGLWINDOWPOS3DPROC func_glWindowPos3d() { return glWindowPos3d; }
PFNGLWINDOWPOS3DVPROC func_glWindowPos3dv() { return glWindowPos3dv; }
PFNGLWINDOWPOS3FPROC func_glWindowPos3f() { return glWindowPos3f; }
PFNGLWINDOWPOS3FVPROC func_glWindowPos3fv() { return glWindowPos3fv; }
PFNGLWINDOWPOS3IPROC func_glWindowPos3i() { return glWindowPos3i; }
PFNGLWINDOWPOS3IVPROC func_glWindowPos3iv() { return glWindowPos3iv; }
PFNGLWINDOWPOS3SPROC func_glWindowPos3s() { return glWindowPos3s; }
PFNGLWINDOWPOS3SVPROC func_glWindowPos3sv() { return glWindowPos3sv; }
